// GENERATED by src/telemetry/schema.rs (bindings_are_current). Do not edit.
// Bless: TELEMETRY_BLESS=1 cargo test --lib telemetry
window.SpellTelemetrySchema = Object.freeze({
  version: 1,
  errorCodes: Object.freeze(["js_uncaught","js_unhandled_rejection","wasm_panic","wasm_init_failed","pack_load_failed","native_crash","native_hang"]),
  jsBufferKey: "spell_tel_jsbuf_v1",
  jsBufferMax: 20,
});
