//! D18 / Done #19–21: the 12×12 Expert seed pack, built and checked.

use super::gen::{grid_at, Clue, Tier};
use super::geo::{Geo, S12};
use super::pack::{config12, entries, entry_for, three_empties_each, Entry};
use super::rng::fnv;
use super::solve::{count_solutions, grade};

/// How many distinct grids the pack carries: more than a player meets in the
/// 365-day repeat window (I6) at several 12×12 boards a day.
pub const PACK_SIZE: usize = 1000;

fn pack_seed(i: u64) -> u64 {
    fnv(format!("spelldoku-pack12|{i}").as_bytes())
}

/// Writes assets/spelldoku/pack12.json. Deterministic: the same seeds, the
/// same order, on any machine.
/// cargo test --release --lib --features audit_preview build_pack12 -- --ignored
#[test]
#[ignore]
fn build_pack12() {
    let want = PACK_SIZE + PACK_SIZE / 10;
    let threads = std::thread::available_parallelism().map(|n| n.get()).unwrap_or(4) as u64;
    let handles: Vec<_> = (0..threads)
        .map(|t| {
            std::thread::spawn(move || {
                let mut found: Vec<(u64, Entry)> = Vec::new();
                let mut i = t;
                while (i as usize) < want {
                    let seed = pack_seed(i);
                    if let Some(e) = (0..4000u64).find_map(|a| entry_for(seed, a)) {
                        found.push((i, e));
                    }
                    i += threads;
                }
                found
            })
        })
        .collect();
    let mut all: Vec<(u64, Entry)> = handles.into_iter().flat_map(|h| h.join().unwrap()).collect();
    all.sort_by_key(|(i, _)| *i);
    let mut seen = std::collections::HashSet::new();
    let entries: Vec<Entry> = all.into_iter().map(|(_, e)| e).filter(|e| seen.insert(e.hash)).take(PACK_SIZE).collect();
    assert_eq!(entries.len(), PACK_SIZE, "not enough distinct grids");
    let body = serde_json::json!({
        "$comment": "GENERATED by src/spelldoku/pack_tests.rs build_pack12 -- do not edit. CC-SPELLDOKU v1.2 D18: 12x12 Expert (seed, attempt) pairs whose grid grades exactly Expert and leaves every symbol three empty cells; hash is the grid's canonical hash (I6). Symbols are bound on the device.",
        "entries": entries,
    });
    let path = format!("{}/assets/spelldoku/pack12.json", env!("CARGO_MANIFEST_DIR"));
    std::fs::write(path, format!("{:#}\n", body)).unwrap();
}

fn check(e: &Entry) {
    let fixed = grid_at(e.seed, e.attempt, &config12()).unwrap_or_else(|| panic!("entry {:x}/{} no longer grades Expert", e.seed, e.attempt));
    let geo = Geo::new(S12);
    let open = vec![geo.full(); 144];
    assert_eq!(count_solutions(&geo, &fixed, &open, 2), 1, "I1: {:x} is not unique", e.seed);
    assert_eq!(grade(&geo, &fixed, &open), Some(Tier::Expert.tech()), "I2: {:x} graded wrong", e.seed);
    assert!(three_empties_each(&fixed), "D17: every symbol keeps three empty cells");
    assert_eq!(entry_for(e.seed, e.attempt), Some(*e), "the recorded hash reproduces");
}

/// Done #20 at gate size: pack entries rebuild exactly, unique and graded.
#[test]
fn pack_entries_rebuild_unique_and_expert() {
    let es = entries();
    assert_eq!(es.len(), PACK_SIZE, "the pack is present");
    let hashes: std::collections::HashSet<u64> = es.iter().map(|e| e.hash).collect();
    assert_eq!(hashes.len(), es.len(), "I6: no two entries are the same grid");
    for e in es.iter().step_by(97) {
        check(e);
    }
}

/// Done #20 in full: every entry. cargo test --release ... pack_every_entry -- --ignored
#[test]
#[ignore]
fn pack_every_entry() {
    for e in entries() {
        check(e);
    }
}


#[test]
fn pack_clues_are_symbol_free() {
    // The pack stores seeds, attempts and hashes only: no symbol, word or language.
    let raw = include_str!("../../assets/spelldoku/pack12.json");
    let v: serde_json::Value = serde_json::from_str(raw).unwrap();
    for e in v["entries"].as_array().unwrap() {
        let keys: Vec<&String> = e.as_object().unwrap().keys().collect();
        assert_eq!(keys.len(), 3, "an entry is seed, attempt and hash");
    }
    let _ = Clue::Empty;
}

use super::bind::Mode;
use super::wordmode::{band_mix, board_from_pack, board_or_number, is_word_mode, Personal};

const LANGS: &[&str] = &["en", "es", "fr", "de", "pt", "pl", "ru", "vi", "ko", "ja", "zh", "fil", "sw", "ar", "hi"];

/// A 12×12 board: unique, graded Expert with its fragment, the fragment
/// necessary, the 8 expert + 4 hard mix (F12), no free spelling (I12), and
/// exactly 36 full spellings to finish it (D17).
fn check_twelve(b: &super::bind::Board) {
    let p = &b.puzzle;
    assert_eq!(p.n, 12);
    let geo = Geo::new(S12);
    let (fixed, restrict) = p.constraints(&b.symbols());
    assert_eq!(count_solutions(&geo, &fixed, &restrict, 2), 1, "{}: I1", b.lang);
    assert_eq!(grade(&geo, &fixed, &restrict), Some(Tier::Expert.tech()), "{}: I2", b.lang);
    let frag = (0..144).filter(|&i| matches!(p.clues[i], Clue::Fragment(_))).any(|i| {
        let mut open = restrict.clone();
        open[i] = geo.full();
        count_solutions(&geo, &fixed, &open, 2) > 1
    });
    assert!(frag, "{}: a necessary fragment", b.lang);
    let Mode::Words(w) = &b.mode else { panic!("12x12 is Word Mode only (D19)") };
    for &(band, count) in band_mix(12, Tier::Expert).unwrap() {
        assert_eq!(w.iter().filter(|s| s.band == band).count(), count, "{}: F12 mix", b.lang);
    }
    let glyphs: std::collections::HashSet<String> = w.iter().map(|s| s.glyph.to_lowercase()).collect();
    assert_eq!(glyphs.len(), 12, "{}: I11", b.lang);
    assert!(!b.spells_a_symbol(), "{}: I12", b.lang);
    // D17 / Done #21: at N=3, every symbol is spelled three times before its chip.
    let need = super::play::unlock_after_on(12, Tier::Expert).unwrap() as usize;
    let spellings: usize = (1..=12u8)
        .map(|v| (0..144).filter(|&i| p.solution[i] == v && !matches!(p.clues[i], Clue::Given(_) | Clue::Spelled(_))).count().min(need))
        .sum();
    assert_eq!(spellings, 36, "{}: Done #21 wants 36 full spellings", b.lang);
}

fn viability(per_lang: usize) {
    let es = entries();
    for lang in LANGS {
        let mut ok = 0;
        for k in 0..per_lang {
            let e = &es[(k * 37) % es.len()];
            if let Some(b) = board_from_pack(lang, e, 900 + k as u64, &Personal::default()) {
                check_twelve(&b);
                ok += 1;
            }
        }
        // Done #19: at least 95%, or the language would not offer 12×12.
        assert!(ok * 100 >= per_lang * 95, "{lang}: 12x12 viable in {ok} of {per_lang}");
    }
}

/// Done #19 and #21 at gate size.
#[test]
fn twelve_by_twelve_plays_in_every_language() {
    viability(3);
}

/// Done #19 in full: 1,000 attempts per language.
/// cargo test --release --lib --features audit_preview twelve_viability_thousand -- --ignored
#[test]
#[ignore]
fn twelve_viability_thousand() {
    viability(1000);
}

/// D17 is scoped to 12×12; D19 cuts 12×12 Number Mode; Spell Jr never sees it.
#[test]
fn twelve_rules() {
    assert_eq!(super::play::unlock_after_on(12, Tier::Expert), Some(3));
    assert_eq!(super::play::unlock_after_on(9, Tier::Expert), None, "a 9x9 Expert board still spells every commit");
    assert!(is_word_mode(false, 12, Tier::Expert));
    let en = super::table::load("en").unwrap();
    assert!(board_or_number("en", false, &config12(), 1, &Personal::default(), Some(&en)).is_none(), "no 12x12 Number Mode");
    assert!(!super::play::allowed(true, 12, Tier::Expert), "Spell Jr never gets 12x12");
    assert!(super::play::allowed(false, 12, Tier::Expert));
}

/// Done #20 / I5: the pinned pack digest. The browser test asks the
/// WebAssembly build for the same number.
pub const PACK_GOLDEN: u64 = 0x14cc1f163b6e7dec;

#[test]
fn the_pack_digest_is_pinned() {
    let got = super::pack::pack_digest();
    assert_eq!(got, PACK_GOLDEN, "pack digest: {got:#x}");
}
