//! CC-LEARNING-ENGINE-L0 **acceptance 3** — the implementation reproduces a
//! published FSRS-4.5 implementation's outputs exactly.
//!
//! C3 pins the algorithm at FSRS-4.5 and asks for "reference outputs from a
//! published FSRS-4.5 implementation, vendored as a fixture". There is no
//! official FSRS vector file — the project ships none — so the reference is
//! another implementation's own hardcoded test expectations, taken at a tag
//! whose source was read and confirmed to be 4.5 rather than trusted by
//! version number. The fixture records which checks established that.
//!
//! TWO INDEPENDENT CHECKS, and they fail for different reasons:
//!
//! 1. `our_weights_are_the_published_fsrs_4_5_defaults` — the CONSTANTS. If
//!    someone bumps `FSRS_W`, this fails even though the arithmetic is fine.
//! 2. `we_reproduce_py_fsrs_2_1_0_test_repeat` — the ARITHMETIC. It runs our
//!    formulas on THEIR parameters, so it fails on a formula error even
//!    though our constants are fine. Running our weights through our own
//!    formulas would only re-assert our own constants and prove nothing.

use spell_wasm::learner::{
    fsrs_review_graded_with, interval_days, FsrsState, Grade, FSRS_D0, FSRS_W,
};

/// The published FSRS-4.5 default parameter set, 17 values. Generated by the
/// FSRS project from 20k collections as the median of 20k fitted sets.
/// Independent of the vector below, which uses its own weights on purpose.
const PUBLISHED_FSRS_4_5_DEFAULTS: [f64; 17] = [
    0.4872, 1.4003, 3.7145, 13.8206, 5.1618, 1.2298, 0.8975, 0.031, 1.6474, 0.1367, 1.0461,
    2.1072, 0.0793, 0.3246, 1.587, 0.2272, 2.8755,
];

#[test]
fn our_weights_are_the_published_fsrs_4_5_defaults() {
    assert_eq!(
        FSRS_W.len(),
        17,
        "FSRS-4.5 has 17 parameters; 19 would mean someone pasted FSRS-5's set"
    );
    for (i, (got, want)) in FSRS_W.iter().zip(PUBLISHED_FSRS_4_5_DEFAULTS.iter()).enumerate() {
        assert!(
            (got - want).abs() < 1e-12,
            "w[{i}] is {got}, the published FSRS-4.5 default is {want}. \
             D3 pins these; changing one is a reviewed change that re-runs the eval suite."
        );
    }
}

/// The reference vector. py-fsrs v2.1.0, `tests/test_fsrs.py::test_repeat`.
///
/// Thirteen reviews produce thirteen intervals, but only ten are memory-state
/// outputs: py-fsrs holds a card in Learning and Relearning for three of them
/// and those steps do not touch S or D. The ten that remain are the core
/// trajectory, and at the 0.9 target retention an FSRS interval reduces to
/// round(S) — the interval formula and FACTOR cancel — so a published
/// interval list IS a published stability trajectory.
#[test]
fn we_reproduce_py_fsrs_2_1_0_test_repeat() {
    // Their weights, not ours. See the fixture for why.
    let w: [f64; 17] = [
        1.14, 1.01, 5.44, 14.67, 5.3024, 1.5662, 1.2503, 0.0028, 1.5489, 0.1763, 0.9953, 2.7473,
        0.0179, 0.3105, 0.3976, 0.0, 2.0902,
    ];
    // (grade, days elapsed since the previous memory update, their interval)
    let vector: &[(Grade, u32, u32)] = &[
        (Grade::Good, 0, 5),
        (Grade::Good, 5, 16),
        (Grade::Good, 16, 43),
        (Grade::Good, 43, 106),
        (Grade::Good, 106, 236),
        (Grade::Again, 236, 12),
        (Grade::Good, 12, 25),
        (Grade::Good, 25, 47),
        (Grade::Good, 47, 85),
        (Grade::Good, 85, 147),
    ];

    let mut f = FsrsState { stability: 0.0, difficulty: FSRS_D0, due_day: 0, reps: 0, lapses: 0 };
    let mut day = 0u32;
    for (n, &(grade, elapsed, want)) in vector.iter().enumerate() {
        day += elapsed;
        fsrs_review_graded_with(&w, &mut f, grade, day);
        let got = interval_days(f.stability);
        assert_eq!(
            got, want,
            "update {} ({:?} after {elapsed}d): we say {got} days, py-fsrs v2.1.0 says {want}. \
             S = {}, D = {}.",
            n + 1,
            grade,
            f.stability,
            f.difficulty,
        );
    }
}

/// The fixture must stay beside the test, and must keep saying where it came
/// from. A vendored reference with no provenance is just a magic number.
#[test]
fn the_vector_is_vendored_with_its_provenance() {
    let raw = include_str!("fixtures/fsrs/py-fsrs-2.1.0-test_repeat.json");
    for needle in ["py-fsrs", "v2.1.0", "test_repeat", "DECAY = -0.5", "19/81"] {
        assert!(raw.contains(needle), "the fixture no longer records {needle:?}");
    }
}

/// A reference test that cannot fail is decoration. This perturbs each
/// weight and asserts the vector NOTICES — and, just as importantly, records
/// the ones it CANNOT notice, because that is the honest measure of how much
/// acceptance 3 actually covers.
///
/// SIX WEIGHTS ARE STRUCTURALLY UNREACHABLE by this vector, verified by
/// doubling each and seeing no change at all:
///
///   w0  initial stability after Again  — the sequence opens with Good, and
///       its only Again lands at reps > 0, which takes the FORGET path
///   w1  initial stability after Hard   — no Hard in the sequence
///   w3  initial stability after Easy   — no Easy, and this engine has no
///       Easy grade at all (D3 removed it)
///   w5  the D0 slope, D0 = w4 − w5·(G−3) — zero for Good, and the lone
///       Again never takes the initial-difficulty path
///   w15 the Hard penalty                — no Hard in the sequence
///   w16 the Easy bonus                  — no Easy, and none exists here
///
/// Of those, w0, w1, w5 and w15 ARE reachable in this engine and are
/// therefore NOT covered by acceptance 3. That gap is in the review record;
/// closing it needs a second vector that opens with Again or Hard.
///
/// The remaining eleven are checked at 2×, not 1%: intervals are whole days,
/// and rounding swallows a 1% nudge to w7, w11, w12 or w14. A perturbation
/// the rounding can hide is not a test.
#[test]
fn the_vector_bites_on_every_weight_it_can_reach() {
    let base: [f64; 17] = [
        1.14, 1.01, 5.44, 14.67, 5.3024, 1.5662, 1.2503, 0.0028, 1.5489, 0.1763, 0.9953, 2.7473,
        0.0179, 0.3105, 0.3976, 0.0, 2.0902,
    ];
    let vector: &[(Grade, u32, u32)] = &[
        (Grade::Good, 0, 5),
        (Grade::Good, 5, 16),
        (Grade::Good, 16, 43),
        (Grade::Good, 43, 106),
        (Grade::Good, 106, 236),
        (Grade::Again, 236, 12),
        (Grade::Good, 12, 25),
        (Grade::Good, 25, 47),
        (Grade::Good, 47, 85),
        (Grade::Good, 85, 147),
    ];
    let run = |w: &[f64; 17]| {
        let mut f =
            FsrsState { stability: 0.0, difficulty: FSRS_D0, due_day: 0, reps: 0, lapses: 0 };
        let mut day = 0u32;
        let mut out = Vec::new();
        for &(grade, elapsed, _) in vector {
            day += elapsed;
            fsrs_review_graded_with(w, &mut f, grade, day);
            out.push(interval_days(f.stability));
        }
        out
    };
    let want: Vec<u32> = vector.iter().map(|v| v.2).collect();
    assert_eq!(run(&base), want, "the baseline no longer matches");

    /// Doubling these changes nothing, because the sequence never reaches
    /// the term that uses them. Pinned as a fact about the vector.
    const UNREACHABLE: [usize; 6] = [0, 1, 3, 5, 15, 16];

    for i in 0..17 {
        let mut w = base;
        w[i] = if w[i] == 0.0 { 0.5 } else { w[i] * 2.0 };
        let moved = run(&w) != want;
        if UNREACHABLE.contains(&i) {
            assert!(
                !moved,
                "w[{i}] is listed unreachable but doubling it moved the trajectory -- \
                 the vector now covers more than the comment claims, which is good news: \
                 update the list and the review record"
            );
        } else {
            assert!(
                moved,
                "doubling w[{i}] changed nothing -- the vector does not constrain it, \
                 so an error in whichever term uses it would pass unnoticed"
            );
        }
    }
}
