//! CC-LEARNING-ENGINE-L0 **acceptance 3** — the implementation reproduces a
//! published FSRS-4.5 implementation's outputs exactly.
//!
//! C3 pins the algorithm at FSRS-4.5 and asks for "reference outputs from a
//! published FSRS-4.5 implementation, vendored as a fixture". There is no
//! official FSRS vector file — the project ships none — so the reference is
//! another implementation's own hardcoded test expectations, taken at a tag
//! whose source was read and confirmed to be 4.5 rather than trusted by
//! version number. The fixture records which checks established that.
//!
//! TWO INDEPENDENT CHECKS, and they fail for different reasons:
//!
//! 1. `our_weights_are_the_published_fsrs_4_5_defaults` — the CONSTANTS. If
//!    someone bumps `FSRS_W`, this fails even though the arithmetic is fine.
//! 2. `we_reproduce_py_fsrs_2_1_0_test_repeat` — the ARITHMETIC. It runs our
//!    formulas on THEIR parameters, so it fails on a formula error even
//!    though our constants are fine. Running our weights through our own
//!    formulas would only re-assert our own constants and prove nothing.

use spell_wasm::learner::{
    fsrs_init_difficulty, fsrs_init_stability, fsrs_next_difficulty, fsrs_next_forget_stability,
    fsrs_next_recall_stability, fsrs_review_graded_with, interval_days, FsrsState, Grade,
    FSRS_D0, FSRS_W,
};

/// The published FSRS-4.5 default parameter set, 17 values. Generated by the
/// FSRS project from 20k collections as the median of 20k fitted sets.
/// Independent of the vector below, which uses its own weights on purpose.
const PUBLISHED_FSRS_4_5_DEFAULTS: [f64; 17] = [
    0.4872, 1.4003, 3.7145, 13.8206, 5.1618, 1.2298, 0.8975, 0.031, 1.6474, 0.1367, 1.0461,
    2.1072, 0.0793, 0.3246, 1.587, 0.2272, 2.8755,
];

#[test]
fn our_weights_are_the_published_fsrs_4_5_defaults() {
    assert_eq!(
        FSRS_W.len(),
        17,
        "FSRS-4.5 has 17 parameters; 19 would mean someone pasted FSRS-5's set"
    );
    for (i, (got, want)) in FSRS_W.iter().zip(PUBLISHED_FSRS_4_5_DEFAULTS.iter()).enumerate() {
        assert!(
            (got - want).abs() < 1e-12,
            "w[{i}] is {got}, the published FSRS-4.5 default is {want}. \
             D3 pins these; changing one is a reviewed change that re-runs the eval suite."
        );
    }
}

/// The reference vector. py-fsrs v2.1.0, `tests/test_fsrs.py::test_repeat`.
///
/// Thirteen reviews produce thirteen intervals, but only ten are memory-state
/// outputs: py-fsrs holds a card in Learning and Relearning for three of them
/// and those steps do not touch S or D. The ten that remain are the core
/// trajectory, and at the 0.9 target retention an FSRS interval reduces to
/// round(S) — the interval formula and FACTOR cancel — so a published
/// interval list IS a published stability trajectory.
#[test]
fn we_reproduce_py_fsrs_2_1_0_test_repeat() {
    // Their weights, not ours. See the fixture for why.
    let w: [f64; 17] = [
        1.14, 1.01, 5.44, 14.67, 5.3024, 1.5662, 1.2503, 0.0028, 1.5489, 0.1763, 0.9953, 2.7473,
        0.0179, 0.3105, 0.3976, 0.0, 2.0902,
    ];
    // (grade, days elapsed since the previous memory update, their interval)
    let vector: &[(Grade, u32, u32)] = &[
        (Grade::Good, 0, 5),
        (Grade::Good, 5, 16),
        (Grade::Good, 16, 43),
        (Grade::Good, 43, 106),
        (Grade::Good, 106, 236),
        (Grade::Again, 236, 12),
        (Grade::Good, 12, 25),
        (Grade::Good, 25, 47),
        (Grade::Good, 47, 85),
        (Grade::Good, 85, 147),
    ];

    let mut f = FsrsState { stability: 0.0, difficulty: FSRS_D0, due_day: 0, reps: 0, lapses: 0 };
    let mut day = 0u32;
    for (n, &(grade, elapsed, want)) in vector.iter().enumerate() {
        day += elapsed;
        fsrs_review_graded_with(&w, &mut f, grade, day);
        let got = interval_days(f.stability);
        assert_eq!(
            got, want,
            "update {} ({:?} after {elapsed}d): we say {got} days, py-fsrs v2.1.0 says {want}. \
             S = {}, D = {}.",
            n + 1,
            grade,
            f.stability,
            f.difficulty,
        );
    }
}

/// The fixture must stay beside the test, and must keep saying where it came
/// from. A vendored reference with no provenance is just a magic number.
#[test]
fn the_vector_is_vendored_with_its_provenance() {
    let raw = include_str!("fixtures/fsrs/py-fsrs-2.1.0-test_repeat.json");
    for needle in ["py-fsrs", "v2.1.0", "test_repeat", "DECAY = -0.5", "19/81"] {
        assert!(raw.contains(needle), "the fixture no longer records {needle:?}");
    }
}

/// A reference test that cannot fail is decoration. This perturbs each
/// weight and asserts the vector NOTICES — and, just as importantly, records
/// the ones it CANNOT notice, because that is the honest measure of how much
/// acceptance 3 actually covers.
///
/// SIX WEIGHTS ARE STRUCTURALLY UNREACHABLE by this vector, verified by
/// doubling each and seeing no change at all:
///
///   w0  initial stability after Again  — the sequence opens with Good, and
///       its only Again lands at reps > 0, which takes the FORGET path
///   w1  initial stability after Hard   — no Hard in the sequence
///   w3  initial stability after Easy   — no Easy, and this engine has no
///       Easy grade at all (D3 removed it)
///   w5  the D0 slope, D0 = w4 − w5·(G−3) — zero for Good, and the lone
///       Again never takes the initial-difficulty path
///   w15 the Hard penalty                — no Hard in the sequence
///   w16 the Easy bonus                  — no Easy, and none exists here
///
/// Of those, w0, w1, w5 and w15 ARE reachable in this engine and are
/// therefore NOT covered by acceptance 3. That gap is in the review record;
/// closing it needs a second vector that opens with Again or Hard.
///
/// The remaining eleven are checked at 2×, not 1%: intervals are whole days,
/// and rounding swallows a 1% nudge to w7, w11, w12 or w14. A perturbation
/// the rounding can hide is not a test.
#[test]
fn the_vector_bites_on_every_weight_it_can_reach() {
    let base: [f64; 17] = [
        1.14, 1.01, 5.44, 14.67, 5.3024, 1.5662, 1.2503, 0.0028, 1.5489, 0.1763, 0.9953, 2.7473,
        0.0179, 0.3105, 0.3976, 0.0, 2.0902,
    ];
    let vector: &[(Grade, u32, u32)] = &[
        (Grade::Good, 0, 5),
        (Grade::Good, 5, 16),
        (Grade::Good, 16, 43),
        (Grade::Good, 43, 106),
        (Grade::Good, 106, 236),
        (Grade::Again, 236, 12),
        (Grade::Good, 12, 25),
        (Grade::Good, 25, 47),
        (Grade::Good, 47, 85),
        (Grade::Good, 85, 147),
    ];
    let run = |w: &[f64; 17]| {
        let mut f =
            FsrsState { stability: 0.0, difficulty: FSRS_D0, due_day: 0, reps: 0, lapses: 0 };
        let mut day = 0u32;
        let mut out = Vec::new();
        for &(grade, elapsed, _) in vector {
            day += elapsed;
            fsrs_review_graded_with(w, &mut f, grade, day);
            out.push(interval_days(f.stability));
        }
        out
    };
    let want: Vec<u32> = vector.iter().map(|v| v.2).collect();
    assert_eq!(run(&base), want, "the baseline no longer matches");

    /// Doubling these changes nothing, because the sequence never reaches
    /// the term that uses them. Pinned as a fact about the vector.
    const UNREACHABLE: [usize; 6] = [0, 1, 3, 5, 15, 16];

    for i in 0..17 {
        let mut w = base;
        w[i] = if w[i] == 0.0 { 0.5 } else { w[i] * 2.0 };
        let moved = run(&w) != want;
        if UNREACHABLE.contains(&i) {
            assert!(
                !moved,
                "w[{i}] is listed unreachable but doubling it moved the trajectory -- \
                 the vector now covers more than the comment claims, which is good news: \
                 update the list and the review record"
            );
        } else {
            assert!(
                moved,
                "doubling w[{i}] changed nothing -- the vector does not constrain it, \
                 so an error in whichever term uses it would pass unnoticed"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// SECOND REFERENCE: ts-fsrs v3.5.6, the component formulas.
//
// The py-fsrs trajectory above cannot reach w0, w1, w5 or w15 — no sequence
// of whole-day reviews opens with both Again and Hard, and it contains no
// Hard at all. These are published PER COMPONENT, so they reach what a
// trajectory cannot. They are also computed at an exact retrievability
// (r = 0.8) that an integer day count cannot produce — the nearest day gives
// 0.79987 — so they can only ever be checked against component functions.
//
// ts-fsrs v3.5.6 is FSRS-4.5: the same test file asserts
// FACTOR == 19/81 == 0.9^(1/DECAY) − 1 with DECAY = −0.5, and its parameter
// vector is 17 long.
// ---------------------------------------------------------------------------

/// ts-fsrs's own weights, as its tests use them.
const TS_FSRS_W: [f64; 17] = [
    0.5701, 1.4436, 4.1386, 10.9355, 5.1443, 1.2006, 0.8627, 0.0362, 1.629, 0.1342, 1.0166,
    2.1174, 0.0839, 0.3204, 1.4676, 0.219, 2.8237,
];

/// ts-fsrs rounds each component with `Decimal.toFixed(8)` before asserting,
/// so 1e-7 is that rounding and nothing more.
const TOL: f64 = 1e-7;

#[test]
fn we_reproduce_ts_fsrs_3_5_6_next_difficulty() {
    // next_difficulty(5.0, grade) for [Again, Hard, Good]. Easy is omitted:
    // D3 removed the grade, so this engine cannot produce it.
    for (grade, want) in [
        (Grade::Again, 6.66816418),
        (Grade::Hard, 5.83669392),
        (Grade::Good, 5.00522366),
    ] {
        let got = fsrs_next_difficulty(&TS_FSRS_W, 5.0, grade);
        assert!(
            (got - want).abs() < TOL,
            "next_difficulty(5.0, {grade:?}) = {got}, ts-fsrs v3.5.6 says {want}"
        );
    }
}

/// **This is the one that closes w15.** Index 1 is the Hard rating, and it
/// is the only published number in either fixture that exercises the hard
/// penalty.
#[test]
fn we_reproduce_ts_fsrs_3_5_6_next_recall_stability() {
    // (d, s, r, grade, expected) — ts-fsrs pairs one (d, s, r) per grade.
    for (d, s, r, grade, want) in [
        // Recall stability computed with an Again rating. No scheduler calls
        // this (an Again takes the forget path) but it is well defined, and
        // it constrains w8, w9 and w10 with no hard penalty in the way.
        (1.0, 5.0, 0.9, Grade::Again, 26.98093855),
        (2.0, 5.0, 0.8, Grade::Hard, 14.12848781),
        (3.0, 5.0, 0.7, Grade::Good, 63.60068241),
    ] {
        let got = fsrs_next_recall_stability(&TS_FSRS_W, d, s, r, grade);
        assert!(
            (got - want).abs() < TOL,
            "next_recall_stability({d}, {s}, {r}, {grade:?}) = {got}, \
             ts-fsrs v3.5.6 says {want}"
        );
    }

    // The point of this whole second reference is that it reaches w15, which
    // nothing else does. Prove the Hard case actually depends on it: neutering
    // the penalty must break that row and leave the others alone.
    let mut neutered = TS_FSRS_W;
    neutered[15] = 1.0;
    let hard = fsrs_next_recall_stability(&neutered, 2.0, 5.0, 0.8, Grade::Hard);
    assert!(
        (hard - 14.12848781).abs() > TOL,
        "setting w15 to 1 did not change the Hard case -- the hard penalty is \
         not actually wired in, and this test proves nothing about it"
    );
    for (d, s, r, grade, want) in [
        (1.0, 5.0, 0.9, Grade::Again, 26.98093855),
        (3.0, 5.0, 0.7, Grade::Good, 63.60068241),
    ] {
        let got = fsrs_next_recall_stability(&neutered, d, s, r, grade);
        assert!(
            (got - want).abs() < TOL,
            "w15 leaked into the {grade:?} case -- the penalty must apply to Hard only"
        );
    }
}

#[test]
fn we_reproduce_ts_fsrs_3_5_6_next_forget_stability() {
    for (d, s, r, want) in [
        (1.0, 5.0, 0.9, 1.9016012),
        (2.0, 5.0, 0.8, 2.0777825),
        (3.0, 5.0, 0.7, 2.3257503),
        (4.0, 5.0, 0.6, 2.62916465),
    ] {
        let got = fsrs_next_forget_stability(&TS_FSRS_W, d, s, r);
        assert!(
            (got - want).abs() < TOL,
            "next_forget_stability({d}, {s}, {r}) = {got}, ts-fsrs v3.5.6 says {want}"
        );
    }
}

/// w0, w1 and w5 are FORMULA CONFORMANCE, not independent reproduction, and
/// the distinction is worth keeping straight.
///
/// Both py-fsrs v2.1.0 and ts-fsrs v3.5.6 *define* initial stability as
/// `w[G−1]` and initial difficulty as `w4 − w5·(G−3)`; ts-fsrs's own tests
/// assert exactly those identities rather than any computed constant. So
/// there is no number out there to disagree with, and no fixture can create
/// one. What this catches is an index off-by-one or a sign error — real
/// mistakes, and the only ones available to make here.
#[test]
fn initial_state_follows_the_published_identities() {
    let w = &TS_FSRS_W;
    // S0(G) = w[G-1]: Again -> w0, Hard -> w1, Good -> w2.
    assert_eq!(fsrs_init_stability(w, Grade::Again), w[0], "S0(Again) must be w0");
    assert_eq!(fsrs_init_stability(w, Grade::Hard), w[1], "S0(Hard) must be w1");
    assert_eq!(fsrs_init_stability(w, Grade::Good), w[2], "S0(Good) must be w2");

    // D0(G) = w4 - w5*(G-3): Again is +2*w5, Hard is +1*w5, Good is exactly w4.
    for (grade, offset) in [(Grade::Again, 2.0), (Grade::Hard, 1.0), (Grade::Good, 0.0)] {
        let want = (w[4] + offset * w[5]).clamp(1.0, 10.0);
        let got = fsrs_init_difficulty(w, grade);
        assert!(
            (got - want).abs() < 1e-12,
            "D0({grade:?}) = {got}, the published identity gives {want} -- a sign error on w5"
        );
    }
    // And Good really is the bare w4, which is the sign error's tell.
    assert!((fsrs_init_difficulty(w, Grade::Good) - w[4]).abs() < 1e-12);
}

#[test]
fn the_second_vector_is_vendored_with_its_provenance() {
    let raw = include_str!("fixtures/fsrs/ts-fsrs-3.5.6-algorithm.json");
    for needle in ["ts-fsrs", "v3.5.6", "algorithm.test.ts", "19/81", "w15"] {
        assert!(raw.contains(needle), "the fixture no longer records {needle:?}");
    }
}
