#!/usr/bin/env python3
"""CC-BANK-PURITY F7 — seed the Spell Jr exclusion lists, mechanically and conservatively.

    python3 tools/bank/seed_kid_lists.py

For every purity language, assets/words/kid-exclude/<lang>.txt gets a generated section (below the marker line;
everything above it is hand-written and never touched) holding
  1. every bank row that is on the language's profanity list (the C6 matches), and
  2. every bank row whose gloss concept (config/gloss/<lang>.json) is an English word on the English Jr list.
Over-exclusion is acceptable (pt `comer` is on a profanity list and will be dropped for children); under-exclusion
is not.  The section is regenerated from the bank, so a row that leaves the bank leaves the list; idempotent.
Auditors extend the lists above the marker (the Gig B sheet has a `not for children` column).
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
from census_c6 import fold_lenient, load
import purity_gate as g

MARK = "# --- CC-BANK-PURITY F7 seed: generated by tools/bank/seed_kid_lists.py, do not hand-edit below this line ---"
HEADER = """# Kid Mode exclusion list — {lang}
# Words filtered from the served pools when Kid Mode is on (the "friendly words"
# promise): alcohol, weapons, death-related, and adult-context terms. One word
# per line (case/accent-insensitive match, lenient fold). Extends the global
# profanity filter — this is the age-appropriateness layer on top.
# ⚠ AUDITOR-EXTENSIBLE: native reviewers should add culture-specific terms above the marker line.
"""

def hand_part(path, lang):
    if not os.path.exists(path):
        return HEADER.format(lang=lang)
    s = open(path, encoding="utf-8").read()
    return (s.split(MARK)[0] if MARK in s else s).rstrip("\n") + "\n"

def main():
    en = {fold_lenient(l.strip()) for l in open(f"{REPO}/assets/words/kid-exclude/en.txt", encoding="utf-8")
          if l.strip() and not l.startswith("#")}
    total = {}
    for lang in g.LANGS + ["vi"]:   # vi is outside the purity spec but is a registered language
        path = f"{REPO}/assets/words/kid-exclude/{lang}.txt"
        prof = load(f"{REPO}/assets/words/profanity/{lang}.txt") or set()
        seeded = {}
        for _, w in g.bank(REPO, lang):
            key = w.rsplit("|", 1)[-1]          # zh rows are pinyin|hanzi; the list matches on the hanzi
            if fold_lenient(key) in prof:
                seeded[key] = "profanity list"
        gp = f"{REPO}/config/gloss/{lang}.json"
        if os.path.exists(gp):
            inbank = {w.rsplit("|", 1)[-1] for _, w in g.bank(REPO, lang)}
            for k, concept in json.load(open(gp, encoding="utf-8"))["rows"].items():
                kk = k.rsplit("|", 1)[-1]
                if kk in inbank and fold_lenient(concept) in en:
                    seeded.setdefault(kk, f"gloss concept: {concept}")
        body = hand_part(path, lang) + MARK + "\n" + "".join(f"{w}\n" for w in sorted(seeded))
        open(path, "w", encoding="utf-8").write(body)
        total[lang] = len(seeded)
    print("seeded:", total)

if __name__ == "__main__":
    main()
