#!/usr/bin/env python3
"""CC-WORDGRID F-S2 / E6 -- build the shipped trap-spelling table for Spell Search.

For every English bank word, apply each confusion edit (config/confusions/en.json)
once, and keep the results that are provably NOT words (I2):
  - not in /usr/share/dict/web2 (E6, signed) or the bank,
  - not a bank or web2 word plus -s, -es, -ed or -ing (web2 has no plurals),
  - not on any profanity list,
  - not the target reversed, and not inside it or around it either way
    (roll / rol would read twice in any grid).

web2 is read here, at build time, and never ships: the app carries only the
decoys that survived it. Spanish and Russian have no such dictionary, so they
get no table and play without decoys (D11).

Run:  python3 tools/wordsearch/build_decoys.py
Out:  assets/wordsearch/en-decoys.txt   (target<TAB>decoy decoy ...)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WEB2 = Path("/usr/share/dict/web2")
OUT = ROOT / "assets" / "wordsearch" / "en-decoys.txt"


def bank(lang):
    src = (ROOT / "src" / "word_data.rs").read_text()
    words = []
    for tier in ("EASY", "MEDIUM", "HARD", "EXPERT"):
        m = re.search(r"pub const %s_%s: &\[&str\] = &\[(.*?)\];" % (lang.upper(), tier), src, re.S)
        if not m:
            sys.exit(f"no {lang} {tier} tier in src/word_data.rs")
        words += [w.split("|")[0].lower() for w in re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))]
    return sorted({w for w in words if w.isascii() and w.isalpha()})


def edits(word, rules):
    """Every string one confusion edit away from `word`. Mirrors
    src/wordsearch/confusion.rs::edits exactly -- a Rust test holds the two to it."""
    out = set()
    vowels = "aeiouy"
    for rule in rules["swaps"]:
        frm, to, at = rule[:3]
        if len(rule) > 3 and len(word) < rule[3]:
            continue
        start = 0
        while True:
            i = word.find(frm, start)
            if i < 0:
                break
            start = i + 1
            if at == "start" and i != 0:
                continue
            if at == "mid" and i == 0:
                continue
            if at == "end" and i + len(frm) != len(word):
                continue
            out.add(word[:i] + to + word[i + len(frm):])
    for i, c in enumerate(word):
        if i == 0:
            continue
        doubled = i + 1 < len(word) and word[i + 1] == c
        if c in rules["single"] and doubled:
            out.add(word[:i] + word[i + 1:])
        between_vowels = word[i - 1] in vowels and i + 1 < len(word) and word[i + 1] in vowels
        if c in rules["double"] and between_vowels:
            out.add(word[:i] + c + word[i:])
    out.discard(word)
    return out


def stems(w):
    """Ways `w` could be a real word with an inflection on it."""
    s = set()
    for suf in ("s", "es", "ed", "ing"):
        if w.endswith(suf) and len(w) > len(suf) + 1:
            b = w[: -len(suf)]
            s.add(b)
            s.add(b + "e")
            if len(b) > 2 and b[-1] == b[-2]:
                s.add(b[:-1])
    for suf in ("ies", "ied"):
        if w.endswith(suf):
            s.add(w[: -len(suf)] + "y")
    return s


def main():
    if not WEB2.exists():
        sys.exit("E6 needs /usr/share/dict/web2 (macOS). Not found.")
    rules = json.loads((ROOT / "config" / "confusions" / "en.json").read_text())
    words = bank("en")
    dictionary = {l.strip().lower() for l in WEB2.read_text().splitlines() if l.strip()}
    dictionary |= set(words)
    blocked = set()
    for f in (ROOT / "assets" / "words" / "profanity").glob("*.txt"):
        for line in f.read_text().splitlines():
            line = line.strip().lower()
            if line and not line.startswith("#"):
                blocked.add(line)

    rows, total = [], 0
    for w in words:
        keep = sorted(
            d for d in edits(w, rules)
            if len(d) >= 3
            and d not in dictionary
            and not (stems(d) & dictionary)
            and d not in blocked
            and d != w[::-1]
            # A decoy inside its target (roll/rol) or around it would read twice.
            and d not in w and w not in d and d[::-1] not in w and w not in d[::-1]
        )
        if keep:
            rows.append(f"{w}\t{' '.join(keep)}")
            total += len(keep)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "# GENERATED by tools/wordsearch/build_decoys.py -- do not edit.\n"
        "# CC-WORDGRID F-S2: one confusion edit each (config/confusions/en.json),\n"
        "# none of them in web2, the bank, their -s/-es/-ed/-ing forms, or a blocklist.\n"
        + "\n".join(rows) + "\n"
    )
    print(f"en: {len(rows)} of {len(words)} bank words have decoys, {total} decoys -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
