#!/usr/bin/env python3
"""Emit src/word_data_audit.rs from assets/words-draft/ (AUDIT PREVIEW ONLY).

These are unverified CC BY-SA drafts (see assets/words-draft/README.md). The
generated module is compiled ONLY under the `audit_preview` cargo feature; the
production build never contains it. Run: python3 scripts/build-draft-wordbanks.py

The upstream drafts were produced from OpenSubtitles frequency lists, validated
against each language's keyboard charset (typeability) + NFC + length, and
Persian-normalised. That fetch/validate step lives in the git history of this
change; this script only re-emits the Rust from the committed .txt files, so the
build is reproducible and offline.
"""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DRAFT = os.path.join(ROOT, "assets", "words-draft")
LANGS = ["ar", "fa", "ur", "ru"]
TIERS = ["easy", "medium", "hard", "expert"]

def esc(w): return w.replace("\\", "\\\\").replace('"', '\\"')

out = ['//! @generated by scripts/build-draft-wordbanks.py — DO NOT EDIT.',
       '//!',
       '//! AUDIT-PREVIEW word banks: unverified CC BY-SA drafts, compiled ONLY under',
       '//! the `audit_preview` feature (see assets/words-draft/README.md). The',
       '//! production build never includes this module.', '']
arms = []
for lang in LANGS:
    for tier in TIERS:
        path = os.path.join(DRAFT, lang, f"{tier}.txt")
        words = [w.strip() for w in open(path, encoding="utf-8") if w.strip()]
        const = f"{lang.upper()}_{tier.upper()}"
        lits = ", ".join(f'"{esc(w)}"' for w in words)
        out.append(f'const {const}: &[&str] = &[{lits}];')
        arms.append(f'        ("{lang}", "{tier}") => {const},')
out.append('')
out.append('/// Draft bank for (lang, tier) under audit preview; empty otherwise.')
out.append('pub fn tier_for(lang: &str, tier: &str) -> &\'static [&\'static str] {')
out.append('    match (lang, tier) {')
out.extend(arms)
out.append('        _ => &[],')
out.append('    }')
out.append('}')
open(os.path.join(ROOT, "src", "word_data_audit.rs"), "w", encoding="utf-8").write("\n".join(out) + "\n")
total = sum(len([w for w in open(os.path.join(DRAFT,l,f"{t}.txt"),encoding="utf-8") if w.strip()]) for l in LANGS for t in TIERS)
print(f"  wrote src/word_data_audit.rs — {len(LANGS)} langs x {len(TIERS)} tiers, {total} draft words")
