#!/usr/bin/env node
// Renders NOTICES.md into notices.html, the ONE attribution page a player can
// actually reach.
//
// WHY THIS EXISTS. NOTICES.md recorded every third-party data licence the app
// depends on -- Leipzig CC BY 4.0, CC-CEDICT CC BY-SA 4.0, Wiktionary
// CC BY-SA 4.0, KANJIDIC2, JMdict-derived JLPT meanings, OpenDyslexic CC BY 3.0
// -- and shipped NOWHERE. Not in dist/, not in the iOS bundle, not served by
// the site; index.html named it only in a CSS comment. The fonts were the one
// part already handled, because fonts/OFL.txt sits inside the fonts/ directory
// that the builds copy wholesale. Found 2026-10-07 while remedying
// docs/census/bank_provenance.md, which had itself missed NOTICES.md and
// concluded the banks were credited nowhere at all.
//
// Committed rather than generated at build time ON PURPOSE. The site's serve
// stage is caddy:2-alpine with no Python and no Node, and five separate build
// scripts assemble their own dist directory. A committed artifact is copied by
// all six the same way any static file is, and scripts/notices-ship-check.mjs
// re-renders NOTICES.md and fails if the two have drifted -- the same shape as
// src/word_data.rs under build-wordlists.py.
//
//   node scripts/build-notices.mjs          # write notices.html
//   node scripts/build-notices.mjs --check   # exit 1 if it is stale
import fs from "node:fs";
import path from "node:path";

const ROOT = path.dirname(new URL(import.meta.url).pathname) + "/..";
export const SRC = path.join(ROOT, "NOTICES.md");
export const OUT = path.join(ROOT, "notices.html");

const esc = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
   .replace(/"/g, "&quot;");

// Deliberately small: headings, bold, inline code, bullets, bare URLs, rules.
// NOTICES.md uses nothing else, and notices-ship-check pins that it does not
// start to -- an unsupported construct would otherwise reach a player as raw
// markdown on the one page that has to be unambiguous.
function inline(s) {
  return esc(s)
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/(?<!["=])\bhttps?:\/\/[^\s<>()]+/g,
             (u) => `<a href="${u}" rel="noopener noreferrer">${u}</a>`);
}

export function render(md) {
  const out = [];
  let list = false;
  let para = [];
  // NOTICES.md is hard-wrapped at ~80 columns, so a paragraph arrives as
  // several lines. Emitting one <p> per LINE broke every paragraph into
  // fragments; join until a blank line, heading, bullet or rule ends it.
  const flush = () => {
    if (para.length) { out.push(`<p>${inline(para.join(" "))}</p>`); para = []; }
  };
  const closeList = () => { if (list) { out.push("</ul>"); list = false; } };
  const endBlock = () => { flush(); closeList(); };
  for (const raw of md.split("\n")) {
    const line = raw.replace(/\s+$/, "");
    if (/^---+$/.test(line)) { endBlock(); out.push("<hr>"); continue; }
    const h = line.match(/^(#{1,3})\s+(.*)$/);
    if (h) { endBlock(); const n = h[1].length; out.push(`<h${n}>${inline(h[2])}</h${n}>`); continue; }
    const li = line.match(/^\s*[-*]\s+(.*)$/);
    if (li) {
      flush();
      if (!list) { out.push("<ul>"); list = true; }
      out.push(`<li>${inline(li[1])}</li>`);
      continue;
    }
    if (!line.trim()) { endBlock(); continue; }
    // An indented continuation of the bullet above keeps that bullet.
    if (list && !para.length && /^\s+\S/.test(raw)) {
      out[out.length - 1] = out[out.length - 1].replace(/<\/li>$/, ` ${inline(line.trim())}</li>`);
      continue;
    }
    closeList();
    para.push(line.trim());
  }
  endBlock();
  return `<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Third-party notices</title>
<!-- GENERATED by scripts/build-notices.mjs from NOTICES.md. Do not hand-edit:
     scripts/notices-ship-check.mjs re-renders the source and fails on drift. -->
<style>
  :root { color-scheme: light dark; --fg: #16181d; --bg: #fbfbfd; --mut: #5b616e; --rule: #d9dce3; --code: #eef0f4; }
  @media (prefers-color-scheme: dark) {
    :root { --fg: #e7e9ee; --bg: #15171c; --mut: #9aa1ae; --rule: #2c3038; --code: #22262e; }
  }
  html { background: var(--bg); }
  body { margin: 0 auto; padding: 24px 16px 64px; max-width: 46rem; background: var(--bg); color: var(--fg);
         font: 16px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; }
  h1 { font-size: 1.5rem; margin: 0 0 .25em; }
  h2 { font-size: 1.15rem; margin: 2em 0 .4em; }
  h3 { font-size: 1rem; margin: 1.5em 0 .3em; color: var(--mut); }
  p { margin: .6em 0; }
  ul { margin: .5em 0; padding-inline-start: 1.25rem; }
  li { margin: .4em 0; }
  code { background: var(--code); padding: .1em .35em; border-radius: 4px; font-size: .9em;
         font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  a { color: inherit; text-decoration: underline; text-underline-offset: 2px; }
  hr { border: 0; border-top: 1px solid var(--rule); margin: 2.5em 0; }
</style>
${out.join("\n")}
</html>
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const html = render(fs.readFileSync(SRC, "utf8"));
  if (process.argv.includes("--check")) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    if (cur !== html) {
      console.error("notices.html is STALE — run: node scripts/build-notices.mjs");
      process.exit(1);
    }
    console.log("notices.html is up to date");
  } else {
    fs.writeFileSync(OUT, html);
    console.log(`wrote notices.html (${html.length} bytes) from NOTICES.md`);
  }
}
