#!/usr/bin/env python3
"""CC-CJK-INK F5 — the stroke-count table the writing Climb is built on.

D7 tiers writing by STROKE COUNT rather than word frequency, because those are
different ladders: 一 is trivial to write and 憂 is not, however common either
word is. That needs a stroke count per character, and the repo had none --
Unicode carries no such property in the character itself.

TWO SOURCES, because the bank holds two kinds of character:

  Han (2234 of them, all zh) -- Unihan's kTotalStrokes, the reference the
  IRG maintains. Downloaded rather than hand-typed; 2234 hand counts would be
  2234 chances to be wrong.

  Hiragana (82, all ja) -- DERIVED, not tabulated. Only the 46 base kana are
  listed here; が is か plus a dakuten and ぱ is は plus a handakuten, so NFD
  decomposition plus a two-stroke and one-stroke rule covers the rest. Listing
  all 82 by hand would have been 36 extra chances to fumble a number that is
  already implied.

Regenerate:  python3 tools/build-stroke-counts.py <path to Unihan_IRGSources.txt>
"""
import pathlib
import re
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent

# The 46 base hiragana. Everything else in the ja bank is one of these plus a
# voicing mark, and that is derived rather than repeated.
BASE_KANA = {
    "あ": 3, "い": 2, "う": 2, "え": 2, "お": 3,
    "か": 3, "き": 4, "く": 1, "け": 3, "こ": 2,
    "さ": 3, "し": 1, "す": 2, "せ": 3, "そ": 1,
    "た": 4, "ち": 2, "つ": 1, "て": 1, "と": 2,
    "な": 4, "に": 3, "ぬ": 2, "ね": 2, "の": 1,
    "は": 3, "ひ": 1, "ふ": 4, "へ": 1, "ほ": 4,
    "ま": 3, "み": 2, "む": 3, "め": 2, "も": 3,
    "や": 3, "ゆ": 2, "よ": 2,
    "ら": 2, "り": 2, "る": 1, "れ": 2, "ろ": 1,
    "わ": 2, "を": 3, "ん": 1,
}
DAKUTEN, HANDAKUTEN = "゙", "゚"
# Small kana (sutegana) are separate codepoints rather than decompositions, so
# they need naming. The count is the base form's: writing a small ゃ is the same
# three strokes as や, just smaller.
SMALL_KANA = {"ぁ": "あ", "ぃ": "い", "ぅ": "う",
              "ぇ": "え", "ぉ": "お", "っ": "つ",
              "ゃ": "や", "ゅ": "ゆ", "ょ": "よ",
              "ゎ": "わ"}


def kana_strokes(ch: str):
    """Strokes for a kana, deriving the voiced forms from their base."""
    d = unicodedata.normalize("NFD", SMALL_KANA.get(ch, ch))
    base = d[0]
    if base not in BASE_KANA:
        return None
    n = BASE_KANA[base]
    for mark in d[1:]:
        if mark == DAKUTEN:
            n += 2          # the two ticks
        elif mark == HANDAKUTEN:
            n += 1          # the small circle
        else:
            return None
    return n


def bank_chars():
    src = (ROOT / "src/words.rs").read_text() + (ROOT / "src/word_data.rs").read_text()
    out = set()
    for lang in ("ZH", "JA"):
        for tier in ("EASY", "MEDIUM", "HARD", "EXPERT"):
            m = re.search(rf"pub const {lang}_{tier}: &\[&str\] = &\[(.*?)\];", src, re.S)
            if not m:
                continue
            for e in re.findall(r'"([^"]+)"', m.group(1)):
                s = e.split("|")[1] if "|" in e else e
                out |= {c for c in s if not c.isascii()}
    return out


def main() -> int:
    if len(sys.argv) < 2:
        sys.exit("usage: build-stroke-counts.py <Unihan_IRGSources.txt>")
    unihan = {}
    for line in pathlib.Path(sys.argv[1]).read_text().splitlines():
        if "kTotalStrokes" not in line or line.startswith("#"):
            continue
        code, _, val = line.split("\t")[:3]
        # Some characters carry two counts (mainland and Taiwan analyses of the
        # same glyph); take the first, which is the one the IRG lists first.
        first = val.split()[0]
        if first.isdigit():
            unihan[chr(int(code[2:], 16))] = int(first)

    rows, missing = [], []
    for ch in sorted(bank_chars()):
        n = unihan.get(ch) or kana_strokes(ch)
        if n is None:
            missing.append(ch)
        else:
            rows.append((ch, n))
    if missing:
        print(f"  {len(missing)} characters have no stroke count: {''.join(missing[:20])}")

    body = "\n".join(f'    ("{c}", {n}),' for c, n in rows)
    (ROOT / "src/stroke_counts.rs").write_text(
        f'''// GENERATED by tools/build-stroke-counts.py -- do not hand-edit.
// CC-CJK-INK F5: strokes per character, for the writing Climb.
//
// {len(rows)} characters: Han counts from Unihan's kTotalStrokes, kana derived
// from the 46 base forms plus their voicing marks. Sorted, so lookup is a
// binary search.
//
// Writing difficulty is strokes; reading difficulty is frequency. They are
// different ladders and this is the one the pad climbs (D7).
pub const STROKES: [(&str, u8); {len(rows)}] = [
{body}
];

/// Strokes for one character, or None if it is not a bank character.
pub fn strokes(ch: &str) -> Option<u8> {{
    STROKES
        .binary_search_by(|(k, _)| (*k).cmp(ch))
        .ok()
        .map(|i| STROKES[i].1)
}}

/// The heaviest character in a word — a word is as hard to write as its worst
/// character, not its average.
pub fn word_strokes(word: &str) -> Option<u8> {{
    let mut worst = None;
    for c in word.chars().filter(|c| !c.is_ascii()) {{
        let n = strokes(&c.to_string())?;
        worst = Some(worst.map_or(n, |w: u8| w.max(n)));
    }}
    worst
}}
'''
    )
    dist = {}
    for _, n in rows:
        dist[n // 5 * 5] = dist.get(n // 5 * 5, 0) + 1
    print(f"  wrote src/stroke_counts.rs — {len(rows)} characters")
    print("  distribution: " + "  ".join(
        f"{k}-{k+4}:{v}" for k, v in sorted(dist.items())))
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
