#!/usr/bin/env python3
"""Distil per-word frequency for the ko and ja banks.

WHY A DISTILLED FILE rather than a dependency. wordfreq ships 58MB of bundled
data and edict2 is another 7.7MB; vendoring either wholesale to answer "how
common is this word" would be absurd. The banks are ~6k words each, so the
useful subset is a two-column text file in exactly the shape freq_en.txt
already has -- small, diffable, reviewable, and consumed by the same pipeline.

JAPANESE NEEDS A JOIN. The bank spells Japanese in KANA; wordfreq indexes
standard KANJI orthography. They are the same words in different scripts and
they do not meet. edict2 supplies reading -> writing, which lifts coverage from
38.2% to 78.4%. Korean needs no join -- both sides are hangul.

Regenerate with:
  pip install wordfreq msgpack
  curl -O http://ftp.edrdg.org/pub/Nihongo/edict2.gz
  python3 tools/build_freq_cjk.py --wordfreq-data <dir> --edict2 edict2.gz

SOURCES, recorded in data/LICENSES.md:
  wordfreq  Apache-2.0
  EDICT2    CC BY-SA, Electronic Dictionary Research & Development Group
"""
import argparse, collections, gzip, pathlib, re, sys

import os
ROOT = pathlib.Path(os.environ.get("SPELL_ROOT",
    pathlib.Path(__file__).resolve().parent.parent))
OUT = ROOT / "tools/wordpipe/sources"


def bank(lang):
    src = (ROOT/"src/words.rs").read_text() + (ROOT/"src/word_data.rs").read_text()
    out = []
    for t in ("EASY", "MEDIUM", "HARD", "EXPERT"):
        m = re.search(rf"pub const {lang.upper()}_{t}: &\[&str\] = &\[(.*?)\];", src, re.S)
        if m:
            out += [e.split("|")[0].strip() for e in re.findall(r'"([^"]+)"', m.group(1))]
    return sorted(set(out))


def wordfreq_ranks(data_dir, lang):
    import msgpack
    for name in (f"large_{lang}.msgpack.gz", f"small_{lang}.msgpack.gz"):
        p = pathlib.Path(data_dir) / name
        if p.exists():
            with gzip.open(p) as fh:
                data = msgpack.load(fh, raw=False)
            rank = {}
            for i, bucket in enumerate(data[1:], start=1):
                for w in bucket:
                    rank.setdefault(w, i)     # lower = more frequent
            return rank
    sys.exit(f"no wordfreq data for {lang} in {data_dir}")


def edict_readings(path):
    """reading -> {writings}. EDICT2 is EUC-JP: KANJI1;KANJI2 [KANA1;KANA2] /gloss/"""
    r2w = collections.defaultdict(set)
    kana_only = set()
    with gzip.open(path) as fh:
        for raw in fh:
            line = raw.decode("euc-jp", errors="ignore").strip()
            if not line or line.startswith("　"):
                continue
            head = line.split("/")[0].strip()
            m = re.match(r"^(\S+?)\s*\[(.+?)\]\s*$", head)
            if m:
                ws = [w.split("(")[0] for w in m.group(1).split(";")]
                for r in m.group(2).split(";"):
                    r2w[r.split("(")[0]].update(ws)
            else:
                for r in head.split(";"):
                    kana_only.add(r.split("(")[0])
    return r2w, kana_only


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--wordfreq-data", required=True)
    ap.add_argument("--edict2", required=True)
    ap.add_argument("--out", default=None)
    a = ap.parse_args()

    out_dir = pathlib.Path(a.out) if a.out else OUT
    out_dir.mkdir(parents=True, exist_ok=True)
    r2w, kana_only = edict_readings(a.edict2)
    for lang in ("ko", "ja"):
        rank = wordfreq_ranks(a.wordfreq_data, lang)
        rows, hit = [], 0
        for w in bank(lang):
            r = rank.get(w)
            if r is None and lang == "ja":
                # the kana->kanji join: take the COMMONEST writing of this
                # reading. A reading with several writings (はし = 橋/箸) is
                # ambiguous by nature; the commonest is the one a learner is
                # most likely to have met, and the alternative is no signal.
                cands = [rank[k] for k in r2w.get(w, ()) if k in rank]
                if cands:
                    r = min(cands)
                elif w in kana_only:
                    r = None
            if r is not None:
                hit += 1
            rows.append((w, r))
        path = out_dir / f"freq_{lang}.txt"
        with path.open("w", encoding="utf-8") as fh:
            fh.write(f"# GENERATED by tools/build_freq_cjk.py -- do not hand-edit.\n")
            fh.write(f"# word <tab> wordfreq band (lower = commoner); blank = no frequency known.\n")
            fh.write(f"# sources: wordfreq (Apache-2.0); EDICT2 (CC BY-SA, EDRDG) for the ja kana->kanji join.\n")
            fh.write(f"# coverage: {hit}/{len(rows)} ({hit/len(rows)*100:.1f}%)\n")
            for w, r in rows:
                fh.write(f"{w}\t{r if r is not None else ''}\n")
        print(f"  {lang}: {hit}/{len(rows)} covered ({hit/len(rows)*100:.1f}%) -> {path.name}")


if __name__ == "__main__":
    main()
