#!/usr/bin/env python3
"""CC-ZH-TONE F5 — derive the sandhi table for every zh bank entry.

Requiring tone forces us to say WHICH tone. 你好 is spoken ni2 hao3; written
pinyin is ni3 hao3. We tell the player to spell what they hear and then mark it
wrong. That conflict has to be designed, not discovered on device.

    pinyinCitation  what grading compares against  (the bank's own left half)
    pinyinSurface   what TTS synthesizes           (sandhi applied)
    sandhiClass     none | third-third | bu | yi

**The tagger PRE-FILLS, it never approves** -- same doctrine as the
dictionary-matcher. Its output is a proposal a human confirms; the 50-word
audit fixture is where that confirmation is recorded.

Why a side table rather than more pipe-delimited fields: src/words.rs entries
are parsed POSITIONALLY in a dozen places, and inconsistently -- game.rs takes
field 2 as the hanzi while kid_filter.rs takes the LAST field. Any extension of
"pinyin|hanzi" breaks one or the other silently. Keyed 1:1 off the whole entry,
nothing that reads the bank today has to change, and the lint still requires a
row for every entry so a missing field is a build failure.

Regenerate:  python3 tools/build-zh-sandhi.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SYL = re.compile(r"[a-zü:]+[0-5]")


def tone_of(syl):
    return int(syl[-1])


def with_tone(syl, tone):
    return syl[:-1] + str(tone)


def apply_sandhi(citation, hanzi):
    """Return (surface, class). Pure, so the rules can be tested directly."""
    sylls = SYL.findall(citation)
    if not sylls:
        return citation, "none"
    out = list(sylls)
    cls = "none"

    # 一 and 不 shift against the tone of what FOLLOWS them, and they are
    # character-specific: a syllable that merely sounds like yi1 does not take
    # 一's sandhi. Positional because Chinese is one character per syllable --
    # entries where that does not hold are reported and left alone.
    chars = [c for c in hanzi if not c.isascii()]
    if len(chars) == len(sylls):
        for i, (syl, ch) in enumerate(zip(sylls, chars)):
            nxt = tone_of(sylls[i + 1]) if i + 1 < len(sylls) else None
            if ch == "一" and tone_of(syl) == 1 and nxt is not None:
                # yi1 -> yi2 before a falling tone, yi4 before the rest.
                out[i] = with_tone(syl, 2 if nxt == 4 else 4)
                cls = "yi"
            elif ch == "不" and tone_of(syl) == 4 and nxt == 4:
                # bu4 -> bu2 only before another falling tone.
                out[i] = with_tone(syl, 2)
                cls = "bu"

    # Third-tone sandhi last, over the ALREADY-shifted tones: in a run of third
    # tones every one but the last rises to second.
    base = [tone_of(s) for s in out]
    shifted = list(out)
    changed = False
    for i in range(len(base) - 1):
        if base[i] == 3 and base[i + 1] == 3:
            shifted[i] = with_tone(out[i], 2)
            changed = True
    if changed:
        out = shifted
        # A word can take both; name the rarer, more specific rule so the class
        # stays useful for teaching. Recorded rather than silently merged.
        if cls == "none":
            cls = "third-third"

    return "".join(out), cls


def main():
    src = (ROOT / "src/words.rs").read_text()
    rows, misaligned = [], []
    counts = {"none": 0, "third-third": 0, "bu": 0, "yi": 0}
    for name in ("ZH_EASY", "ZH_MEDIUM", "ZH_HARD", "ZH_EXPERT"):
        m = re.search(rf"pub const {name}: &\[&str\] = &\[(.*?)\n\];", src, re.S)
        if not m:
            sys.exit(f"{name} not found in src/words.rs")
        for entry in re.findall(r'"([^"]+)"', m.group(1)):
            citation, hanzi = entry.split("|", 1)
            sylls = SYL.findall(citation)
            chars = [c for c in hanzi if not c.isascii()]
            if len(chars) != len(sylls):
                misaligned.append(entry)
            surface, cls = apply_sandhi(citation, hanzi)
            counts[cls] += 1
            rows.append((entry, surface, cls))

    rows.sort(key=lambda r: r[0])
    body = "\n".join(f'    ("{e}", "{s}", "{c}"),' for e, s, c in rows)
    (ROOT / "src/zh_sandhi.rs").write_text(
        f'''// GENERATED by tools/build-zh-sandhi.py -- do not hand-edit.
// CC-ZH-TONE F5: sandhi for every zh bank entry.
//
// Each row is (bank entry, pinyinSurface, sandhiClass). The entry IS the
// citation plus its hanzi, so pinyinCitation is not duplicated here -- it is
// the left half of the key, which is what grading already compares against.
//
// Sorted by entry, so lookup is a binary search. A row for EVERY bank entry is
// required: scripts/zh-bank-sandhi-check.mjs fails the build on a missing one,
// because a word with no surface form is a word TTS cannot speak.
//
// The tagger pre-fills; a human confirms. See the 50-word audit fixture.
//
// {counts["none"]} none, {counts["third-third"]} third-third, {counts["bu"]} bu, {counts["yi"]} yi.
pub const SANDHI: [(&str, &str, &str); {len(rows)}] = [
{body}
];

/// The spoken form of a bank entry, and why it differs. `None` means the entry
/// is not in the bank -- callers must treat that as a build-time bug, never as
/// "no sandhi".
pub fn lookup(entry: &str) -> Option<(&'static str, &'static str)> {{
    SANDHI
        .binary_search_by(|(k, _, _)| (*k).cmp(entry))
        .ok()
        .map(|i| (SANDHI[i].1, SANDHI[i].2))
}}
'''
    )
    print(f"  wrote src/zh_sandhi.rs -- {len(rows)} rows")
    print(f"  {counts['none']} none, {counts['third-third']} third-third, "
          f"{counts['bu']} bu, {counts['yi']} yi")
    if misaligned:
        print(f"  NOTE: {len(misaligned)} entries where syllables and characters do not")
        print(f"        line up 1:1, so 一/不 could not be located; left unshifted.")
        for e in misaligned[:8]:
            print(f"          {e}")


if __name__ == "__main__":
    main()
