#!/usr/bin/env python3
"""CC-ZH-TONE F1a — generate the pinned Mandarin syllable inventory.

Three sources, reconciled rather than trusted individually:

  1. pypinyin's PINYIN_DICT, the authoritative reading table;
  2. the shipped zh bank (src/words.rs ZH_*), which proves every syllable a
     player can actually be asked for is present;
  3. the standard-Mandarin review list below, which flags the readings
     pypinyin carries that are dialectal, interjection-only, or tied to a
     non-standard character.

Source 2 is a HARD gate: a bank syllable missing from the inventory would make
that word unanswerable, so the build fails rather than shipping the gap. Source
3 is advisory -- it annotates, it does not exclude. Over-inclusion only changes
a typo's error class; under-inclusion breaks a real word, and that asymmetry
decides the policy.

Note the bank stores the `v` encoding (lv4, nv3hai2), not `ü`. D2 folds v -> ü
on input, so the inventory holds the ü form and the bank is normalized before
comparison.

Regenerate:  python3 tools/build-pinyin-inventory.py
The pin in the generated file must change in the same commit as the list.
"""
import hashlib
import json
import pathlib
import re
import subprocess
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
VENV_PY = pathlib.Path(
    "/private/tmp/claude-501/-Users-eric/d5d833c7-982c-4f16-9353-8fe37d983a28"
    "/scratchpad/zhvenv/bin/python"
)

# Tone marks only. The diaeresis on ü is NOT one -- stripping every combining
# character would fold lü into lu and merge two distinct syllables.
TONE_MARKS = {"\u0304", "\u0301", "\u030c", "\u0300"}

# Source 3. Carried by pypinyin, but not standard Putonghua answers: dialect
# readings, bare interjections with no written tone convention, and one
# non-standard character. Recorded so the decision is visible in review;
# they are KEPT (see module docstring).
NONSTANDARD = {
    "biang": "non-standard character (biangbiang noodles)",
    "fiao": "dialectal, 覅 only",
    "rua": "dialectal, 挼",
    "cei": "dialectal, 㧟",
    "den": "dialectal, 扽",
    "din": "dialectal",
    "len": "dialectal",
    "nia": "dialectal",
    "bong": "dialectal",
    "hm": "interjection, no tone convention",
    "hng": "interjection, no tone convention",
    "m": "interjection, no tone convention",
    "n": "interjection, no tone convention",
    "ng": "interjection, no tone convention",
}


def toneless(s):
    d = unicodedata.normalize("NFD", s)
    return unicodedata.normalize("NFC", "".join(c for c in d if c not in TONE_MARKS))


def from_pypinyin():
    code = (
        "import json,unicodedata\n"
        "from pypinyin.constants import PINYIN_DICT\n"
        "M={'\\u0304','\\u0301','\\u030c','\\u0300'}\n"
        "def t(s):\n"
        "    d=unicodedata.normalize('NFD',s)\n"
        "    return unicodedata.normalize('NFC',''.join(c for c in d if c not in M))\n"
        "o=set()\n"
        "for v in PINYIN_DICT.values():\n"
        "    for r in v.split(','):\n"
        "        r=r.strip()\n"
        "        if r: o.add(t(r))\n"
        "print(json.dumps(sorted(o)))\n"
    )
    py = str(VENV_PY) if VENV_PY.exists() else sys.executable
    out = subprocess.run([py, "-c", code], capture_output=True, text=True)
    if out.returncode:
        sys.exit(f"pypinyin unavailable ({py}):\n{out.stderr.strip()}")
    return set(json.loads(out.stdout))


def from_bank():
    src = (ROOT / "src/words.rs").read_text()
    syl = set()
    for name in ("ZH_EASY", "ZH_MEDIUM", "ZH_HARD", "ZH_EXPERT"):
        m = re.search(rf"pub const {name}: &\[&str\] = &\[(.*?)\n\];", src, re.S)
        if not m:
            sys.exit(f"{name} not found in src/words.rs")
        for entry in re.findall(r'"([^"]+)"', m.group(1)):
            for s in re.findall(r"[a-zü:]+[0-5]?", entry.split("|")[0]):
                # D2: the bank's v-encoding folds to ü before lookup.
                syl.add(re.sub(r"[0-5]$", "", s).replace("u:", "ü").replace("v", "ü"))
    return syl


def main():
    py, bank = from_pypinyin(), from_bank()
    missing = sorted(bank - py)
    if missing:
        sys.exit(
            "FAIL: bank syllables absent from the inventory -- these words "
            f"would be unanswerable: {missing}"
        )
    inv = sorted(py)
    pin = hashlib.sha256("\n".join(inv).encode()).hexdigest()
    flagged = sorted(set(inv) & set(NONSTANDARD))

    rows = "\n".join(f'    "{s}",' for s in inv)
    notes = "\n".join(f"//   {s:<6} {NONSTANDARD[s]}" for s in flagged)
    flag_rows = "\n".join(f'    "{s}",' for s in flagged)
    (ROOT / "src/pinyin_inventory.rs").write_text(
        f"""// GENERATED by tools/build-pinyin-inventory.py -- do not hand-edit.
// CC-ZH-TONE F1a: the pinned Mandarin syllable inventory.
//
// {len(inv)} toneless syllables, reconciled across pypinyin, the shipped zh
// bank, and a standard-Mandarin review list. Every syllable the bank can ask
// for is present -- the generator fails the build otherwise.
//
// Held in the ü form. D2 folds the v and u: input encodings before lookup.
//
// Kept but flagged as outside standard Putonghua ({len(flagged)}):
{notes}
//
// The pin below is asserted by a test, so changing the list without changing
// the pin fails CI, and changing both shows up as a reviewable diff.
pub const INVENTORY_PIN: &str = "{pin}";

/// Sorted, so lookup is a binary search.
pub const SYLLABLES: [&str; {len(inv)}] = [
{rows}
];

/// The flagged subset, sorted. These are legal answers, but a bare interjection
/// like `n` or `m` also matches inside longer strings and invents segmentations
/// no player meant -- `xian` would greedily read as `xia` + `n`. Segmentation
/// therefore prefers parses that use none of these.
pub const NONSTANDARD: [&str; {len(flagged)}] = [
{flag_rows}
];
"""
    )
    print(f"  wrote src/pinyin_inventory.rs -- {len(inv)} syllables")
    print(f"  pin {pin}")
    print(f"  bank coverage {len(bank)}/{len(bank)} (0 unanswerable)")
    print(f"  flagged non-standard, kept: {' '.join(flagged)}")


if __name__ == "__main__":
    main()
