//! CC-SPELLDOKU v1.3 Done #11 — the Gig B audit sheet for Tier Mode.
//!
//! Tier Mode is a setting inside SpellDoku (D-T1, F9), so every board below is
//! reachable in a TestFlight build by choosing the language, the board tier and
//! Tier Mode in Settings — there is no dev-only door to open. What a build
//! cannot show the auditor is WHICH words a board will serve, so this emits it:
//! one board per English board tier, and one board per other language at the
//! deepest tier it offers (F5), with the ladder and the words each digit draws.
//!
//! Run: `SD_TIER_PREVIEW_OUT=docs/census/spelldoku_tier_preview.md \
//!       cargo test --lib spelldoku_tier_preview -- --ignored --nocapture`

#[test]
#[ignore]
fn spelldoku_tier_preview() {
    use crate::spelldoku::gen::Tier;
    use crate::spelldoku::tier::{self, Session};

    const BOARDS: [(Tier, &str); 4] =
        [(Tier::Easy, "Easy"), (Tier::Medium, "Medium"), (Tier::Hard, "Hard"), (Tier::Expert, "Expert")];
    // One board is 81 cells: every digit lands nine times.
    const PER_DIGIT: usize = 9;

    let mut out = String::from(
        "# CC-SPELLDOKU v1.3 — Tier Mode preview boards (Done #11)\n\n\
         Generated by `cargo test --lib spelldoku_tier_preview -- --ignored`.\n\
         Each block is one playable board: the seed reproduces it, and each digit\n\
         lists the nine words that digit serves on that board, in draw order.\n\n",
    );

    let mut block = |lang: &str, board: Tier, name: &str, seed: u64, out: &mut String| {
        out.push_str(&format!("## {lang} — {name} board (seed {seed})\n\n"));
        out.push_str("| digit | tier | words |\n|---:|---|---|\n");
        let mut s = Session::new(lang, board, false, false, seed);
        for d in 1..=9u8 {
            let band = tier::band(board, d).unwrap();
            let words: Vec<String> = (0..PER_DIGIT)
                .map(|_| s.draw(d).map(|w| w.spelling).unwrap_or_else(|| "—".into()))
                .collect();
            out.push_str(&format!("| {d} | {band} | {} |\n", words.join(", ")));
        }
        out.push('\n');
    };

    for (i, (board, name)) in BOARDS.iter().enumerate() {
        assert!(tier::available("en", *board), "Done #11: English must offer {name}");
        block("en", *board, name, 1000 + i as u64, &mut out);
    }
    for (lang, _n, _s, _d) in crate::consts::BUILTIN_LANGS {
        if lang == "en" {
            continue;
        }
        let deepest = BOARDS.iter().rev().find(|(b, _)| tier::available(lang, *b));
        match deepest {
            Some((board, name)) => block(lang, *board, name, 2000, &mut out),
            None => out.push_str(&format!("## {lang}\n\nNot offered: no board tier passes F5.\n\n")),
        }
    }
    match std::env::var("SD_TIER_PREVIEW_OUT") {
        Ok(p) => std::fs::write(p, &out).unwrap(),
        Err(_) => println!("{out}"),
    }
}
