//! `LANGUAGES` is used only for the "Speak in" voice picker in the Import
//! ("My Words") modal. The built-in word banks that back normal play live in
//! `word_data.rs` — a @generated file produced by `scripts/build-wordlists.py`
//! from the curated sources in `assets/words/{code}/{tier}.txt` (edit those and
//! re-run the pipeline; never edit `word_data.rs` by hand). Their audio is
//! fetched from the backend's `/api/speak`.

use crate::word_data::*;

pub struct LangInfo {
    pub name: &'static str,
    pub code: &'static str,
}

pub const LANGUAGES: [(&str, LangInfo); 18] = [
    ("en", LangInfo { name: "English", code: "en-US" }),
    ("es", LangInfo { name: "Espa\u{f1}ol", code: "es-ES" }),
    ("fr", LangInfo { name: "Fran\u{e7}ais", code: "fr-FR" }),
    ("de", LangInfo { name: "Deutsch", code: "de-DE" }),
    ("pt", LangInfo { name: "Portugu\u{ea}s", code: "pt-BR" }),
    ("pl", LangInfo { name: "Polski", code: "pl-PL" }),
    // CC-LINEUP-SWAP D3 variants: Russian standard ru-RU; Modern Standard
    // Arabic; Iranian Persian (fa-IR, not Dari); Urdu ur-PK standard. Audio is
    // direction-agnostic, so the three RTL languages carry voices here even
    // though the rtl_required gate keeps them off every playable surface.
    ("ru", LangInfo { name: "\u{420}\u{443}\u{441}\u{441}\u{43a}\u{438}\u{439}", code: "ru-RU" }),
    ("ar", LangInfo { name: "\u{627}\u{644}\u{639}\u{631}\u{628}\u{64a}\u{629}", code: "ar-SA" }),
    ("fa", LangInfo { name: "\u{641}\u{627}\u{631}\u{633}\u{6cc}", code: "fa-IR" }),
    ("ur", LangInfo { name: "\u{627}\u{631}\u{62f}\u{648}", code: "ur-PK" }),
    // New languages with their own keyboard + backend voice (My Words matches).
    ("vi", LangInfo { name: "Ti\u{1ebf}ng Vi\u{1ec7}t", code: "vi-VN" }),
    ("ko", LangInfo { name: "\u{d55c}\u{ad6d}\u{c5b4}", code: "ko-KR" }),
    ("ja", LangInfo { name: "\u{65e5}\u{672c}\u{8a9e}", code: "ja-JP" }),
    ("fil", LangInfo { name: "Filipino", code: "fil-PH" }),
    // Mandarin: native audio for imported hanzi (the pinyin keyboard can't type
    // arbitrary hanzi, so My Words Chinese keeps the English layout).
    ("zh", LangInfo { name: "\u{4e2d}\u{6587}", code: "cmn-CN" }),
    ("ro", LangInfo { name: "Rom\u{e2}n\u{103}", code: "ro-RO" }),
    ("id", LangInfo { name: "Indonesia", code: "id-ID" }),
    ("ca", LangInfo { name: "Catal\u{e0}", code: "ca-ES" }),
];

pub fn en_tier(tier: &str) -> &'static [&'static str] {
    match tier {
        "easy" => EN_EASY,
        "medium" => EN_MEDIUM,
        "hard" => EN_HARD,
        "expert" => EN_EXPERT,
        _ => EN_MEDIUM,
    }
}

pub fn es_tier(tier: &str) -> &'static [&'static str] {
    match tier {
        "easy" => ES_EASY,
        "medium" => ES_MEDIUM,
        "hard" => ES_HARD,
        "expert" => ES_EXPERT,
        _ => ES_MEDIUM,
    }
}

fn simple_tier(easy: &'static [&'static str], medium: &'static [&'static str], hard: &'static [&'static str], expert: &'static [&'static str], tier: &str) -> &'static [&'static str] {
    match tier {
        "easy" => easy,
        "medium" => medium,
        "hard" => hard,
        "expert" => expert,
        _ => medium,
    }
}

// Mandarin: entries are "pinyin|hanzi" — the pinyin (before '|') is the typed
// answer, the hanzi (after '|') is what TTS speaks + what's revealed. The first
// 150/150/200/200 per tier are the hand-curated, native-review-flagged core
// (2-syllable, homophone-disambiguated); the rest are Leipzig corpus additions.
// @generated tails — edit assets/words/zh/{tier}.txt and re-run:
//   python3 scripts/build-zh-bank.py
// Not run through build-wordlists.py (its charset gate is for single-string
// words); the keyboard charset test validates the pinyin side separately.
pub const ZH_EASY: &[&str] = &[
    "wo3men5|我们",
    "mei2you3|没有",
    "ta1men5|他们",
    "shen2me5|什么",
    "xian4zai4|现在",
    "zhi1dao4|知道",
    "shi2hou5|时候",
    "gong1zuo4|工作",
    "ni3men5|你们",
    "shi2jian1|时间",
    "zen3me5|怎么",
    "zhe4xie1|这些",
    "xi3huan5|喜欢",
    "hai2you3|还有",
    "jin1tian1|今天",
    "hai2shi5|还是",
    "jue2de5|觉得",
    "kan4dao4|看到",
    "yi1qi3|一起",
    "qi3lai5|起来",
    "yi1xie1|一些",
    "zhao3dao4|找到",
    "fei1chang2|非常",
    "hai2zi5|孩子",
    "zhe4li3|这里",
    "dong1xi1|东西",
    "yi1yang4|一样",
    "zhong4yao4|重要",
    "gao4su4|告诉",
    "di4fang1|地方",
    "chu1lai2|出来",
    "zui4hou4|最后",
    "peng2you5|朋友",
    "de2dao4|得到",
    "na4xie1|那些",
    "zhun3bei4|准备",
    "guo2jia1|国家",
    "dian4hua4|电话",
    "nü3ren2|女人",
    "xiao3shi2|小时",
    "you3xie1|有些",
    "bie2ren5|别人",
    "nan2ren2|男人",
    "zheng4zai4|正在",
    "xue2xiao4|学校",
    "shen1shang5|身上",
    "ren4shi5|认识",
    "ming2tian1|明天",
    "hui2lai5|回来",
    "wan3shang5|晚上",
    "xie4xie5|谢谢",
    "duo1shao3|多少",
    "ma1ma5|妈妈",
    "di4er4|第二",
    "bie2de5|别的",
    "dian4ying3|电影",
    "hui2jia1|回家",
    "zuo2tian1|昨天",
    "xian1sheng5|先生",
    "yi1yuan4|医院",
    "zhen1de5|真的",
    "xue2sheng5|学生",
    "er2zi5|儿子",
    "ming2bai5|明白",
    "ji4de5|记得",
    "zhong1guo2|中国",
    "shen1ti3|身体",
    "na3li3|哪里",
    "na4li5|那里",
    "jie4shao4|介绍",
    "dian4shi4|电视",
    "xia4wu3|下午",
    "chu1qu4|出去",
    "xue2xi2|学习",
    "lao3shi1|老师",
    "da4xue2|大学",
    "yi1sheng1|医生",
    "ming2zi5|名字",
    "ta1men5|她们",
    "ma3shang4|马上",
    "jin1nian2|今年",
    "shou3ji1|手机",
    "kan4jian4|看见",
    "ting1dao4|听到",
    "nü3er2|女儿",
    "shuo1hua4|说话",
    "qi4che1|汽车",
    "ba4ba5|爸爸",
    "gao1xing4|高兴",
    "qu4nian2|去年",
    "lai2dao4|来到",
    "shui4jiao4|睡觉",
    "dian4nao3|电脑",
    "hui2dao4|回到",
    "jia1li3|家里",
    "bu4yong4|不用",
    "ren4zhen1|认真",
    "fang2zi5|房子",
    "fei1ji1|飞机",
    "zao3shang5|早上",
    "hui2da2|回答",
    "hui2qu5|回去",
    "da3kai1|打开",
    "bing4ren2|病人",
    "da3dian4hua4|打电话",
    "xiu1xi5|休息",
    "yi1bian1|一边",
    "you3de5|有的",
    "wang4ji4|忘记",
    "fang2jian1|房间",
    "chi1fan4|吃饭",
    "dong4zuo4|动作",
    "yi1fu5|衣服",
    "shang4ban1|上班",
    "sheng1ri4|生日",
    "jie3jie5|姐姐",
    "yi1ban4|一半",
    "jia1ren2|家人",
    "you3shi2|有时",
    "xiao3jie5|小姐",
    "dui4bu5qi3|对不起",
    "jin4qu4|进去",
    "ge1ge5|哥哥",
    "mei2shen2me5|没什么",
    "lu4shang5|路上",
    "tian1qi4|天气",
    "zui4hao3|最好",
    "kao3shi4|考试",
    "you3shi2hou5|有时候",
    "pang2bian1|旁边",
    "tong2xue2|同学",
    "bang1mang2|帮忙",
    "jin4lai2|进来",
    "jian4mian4|见面",
    "hao3kan4|好看",
    "zhong1jian1|中间",
    "nü3sheng1|女生",
    "di4dian3|地点",
    "xing1qi1|星期",
    "che1shang4|车上",
    "mei4mei5|妹妹",
    "sheng1qi4|生气",
    "di4shang5|地上",
    "shang4wu3|上午",
    "yi1hui4r5|一会儿",
    "ji4zhu5|记住",
    "xia4ci4|下次",
    "zhi1shi5|知识",
    "ji1chang3|机场",
    "xue2yuan4|学院",
    "yi2ge4|一个",
    "di4yi1|第一",
    "ren2kou3|人口",
    "ri4ben3|日本",
    "biao3shi4|表示",
    "xiang1gang3|香港",
    "wen2hua4|文化",
    "zuo4pin3|作品",
    "mei3guo2|美国",
    "cheng2li4|成立",
    "zheng4zhi4|政治",
    "di4san1|第三",
    "ran2er2|然而",
    "zhe4ge5|这个",
    "tong1chang2|通常",
    "hai3ba2|海拔",
    "li4ru2|例如",
    "gong1li3|公里",
    "zeng1jia1|增加",
    "ju4you3|具有",
    "tong2nian2|同年",
    "jiao4yu4|教育",
    "zui4gao1|最高",
    "jue2se4|角色",
    "xing2cheng2|形成",
    "xi4lie4|系列",
    "wei4yu2|位于",
    "tai2wan1|台湾",
    "cheng1wei2|称为",
    "ping2jun1|平均",
    "ci3wai4|此外",
    "gong1cheng2|工程",
    "qu3de2|取得",
    "da4liang4|大量",
    "nian2dai4|年代",
    "mi4du4|密度",
    "zhi2dao4|直到",
    "qian2wang3|前往",
    "shi3de5|使得",
    "ban3ben3|版本",
    "bei3jing1|北京",
    "quan2guo2|全国",
    "bao1han2|包含",
    "shang4hai3|上海",
    "chu1ban3|出版",
    "guo2ji4|国际",
    "mian4ji1|面积",
    "xiang1tong2|相同",
    "wan2jia1|玩家",
    "shi4ji4|世纪",
    "jiao1tong1|交通",
    "gong4you3|共有",
    "xing2shi4|形式",
    "dan1ren4|担任",
    "zhe4zhong3|这种",
    "ying1guo2|英国",
    "qi1jian1|期间",
    "gong1neng2|功能",
    "zhu3xi2|主席",
    "jing1ji4|经济",
    "xing2zheng4|行政",
    "fang1xiang4|方向",
    "ju1min2|居民",
    "tie3lu4|铁路",
    "ji1wei4|积为",
    "yi3xia4|以下",
    "zao1dao4|遭到",
    "xuan1bu4|宣布",
    "ying1wen2|英文",
    "yi3shang4|以上",
    "shi4zhen4|市镇",
    "zhi3chu1|指出",
    "di4si4|第四",
    "gong4tong2|共同",
    "dao3zhi4|导致",
    "zui4chu1|最初",
    "su4du4|速度",
    "tui1chu1|推出",
    "miao2shu4|描述",
    "hen3duo1|很多",
    "mu4di4|目的",
    "dao4lu4|道路",
    "fa3guo2|法国",
    "mei3nian2|每年",
    "yan3chu1|演出",
    "zhu4ming2|著名",
    "ming4ming2|命名",
    "yuan2ben3|原本",
    "tu3di4|土地",
    "jie2gou4|结构",
    "zu3cheng2|组成",
    "zong1jiao4|宗教",
    "guan1fang1|官方",
    "dang1di4|当地",
    "cai3yong4|采用",
    "bo1chu1|播出",
    "gong1gong4|公共",
    "hang2kong1|航空",
    "nan2xing4|男性",
    "quan2qiu2|全球",
    "yin4du4|印度",
    "di4wei4|地位",
    "cheng2yuan2|成员",
    "lie4che1|列车",
    "de2guo2|德国",
    "yun4dong4|运动",
    "jiao4shou4|教授",
    "zhu3ren4|主任",
    "wu3qi4|武器",
    "shen1fen4|身份",
    "da4xing2|大型",
    "min2zu2|民族",
    "zao3qi1|早期",
    "zhi4du4|制度",
    "nü3zi3|女子",
    "ji1che1|机车",
    "sheng1chan3|生产",
    "jian4she4|建设",
    "ji1gou4|机构",
    "zhuan1ji2|专辑",
    "zhan4zheng1|战争",
    "zhu3jue2|主角",
    "qi2hou4|其后",
    "yuan2hui4|员会",
    "pai2ming2|排名",
    "fen1bie2|分别",
    "qu4shi4|去世",
    "ke1ji4|科技",
    "gai1di4|该地",
    "gong1chi3|公尺",
    "che1zhan4|车站",
    "shu4ju4|数据",
    "yong4yu2|用于",
    "zu2qiu2|足球",
    "qing1nian2|青年",
    "liang3ge4|两个",
    "duo1ci4|多次",
    "yin1er2|因而",
    "xian4zhi4|限制",
    "fa1xing2|发行",
    "ti2gao1|提高",
    "gai3ge2|改革",
    "bu4jiu3|不久",
    "wen2wu4|文物",
    "da2dao4|达到",
    "te4shu1|特殊",
    "du2li4|独立",
    "nei4rong2|内容",
    "min2zhu3|民主",
    "cheng2du4|程度",
];
pub const ZH_MEDIUM: &[&str] = &[
    "zi4ji3|自己",
    "ke3yi3|可以",
    "yi3jing1|已经",
    "zhe4yang4|这样",
    "ru2guo3|如果",
    "yin1wei4|因为",
    "wen4ti2|问题",
    "dan4shi4|但是",
    "ke3neng2|可能",
    "suo3yi3|所以",
    "na4me5|那么",
    "zhe4me5|这么",
    "ren4wei2|认为",
    "ying1gai1|应该",
    "da4jia1|大家",
    "fa1xian4|发现",
    "yi1ding4|一定",
    "yi1zhi2|一直",
    "sheng1huo2|生活",
    "bu4guo4|不过",
    "gong1si1|公司",
    "bu4yao4|不要",
    "suo3you3|所有",
    "er2qie3|而且",
    "bi4xu1|必须",
    "cheng2wei2|成为",
    "qi2ta1|其他",
    "shi4qing5|事情",
    "gan3jue2|感觉",
    "ran2hou4|然后",
    "wei4shen2me5|为什么",
    "jin4xing2|进行",
    "chu1xian4|出现",
    "jian4dao4|见到",
    "tong1guo4|通过",
    "guo4qu4|过去",
    "can1jia1|参加",
    "an1quan2|安全",
    "jie1guo3|结果",
    "huo4zhe3|或者",
    "bu4cuo4|不错",
    "ji1hui4|机会",
    "wan2quan2|完全",
    "ji4hua4|计划",
    "ke3shi4|可是",
    "yi3hou4|以后",
    "yao1qiu2|要求",
    "xiang1xin4|相信",
    "sui1ran2|虽然",
    "yuan2yin1|原因",
    "zhi3yao4|只要",
    "jin4ru4|进入",
    "bu4tong2|不同",
    "you3ren2|有人",
    "fen1zhong1|分钟",
    "jie1shou4|接受",
    "qi2zhong1|其中",
    "ren2men5|人们",
    "neng2gou4|能够",
    "wan2cheng2|完成",
    "bang1zhu4|帮助",
    "nu3li4|努力",
    "dang1shi2|当时",
    "bu4fen5|部分",
    "yi3qian2|以前",
    "ban4fa3|办法",
    "te4bie2|特别",
    "zhen1zheng4|真正",
    "gai3bian4|改变",
    "li2kai1|离开",
    "tong2shi2|同时",
    "yi3wei2|以为",
    "fang1fa3|方法",
    "zhi2jie1|直接",
    "ying3xiang3|影响",
    "yong3yuan3|永远",
    "ye3xu3|也许",
    "fang1mian4|方面",
    "huo2dong4|活动",
    "xin4xi1|信息",
    "zui4jin4|最近",
    "kuai4le4|快乐",
    "shi3yong4|使用",
    "lai2zi4|来自",
    "jian3cha2|检查",
    "zhong1xin1|中心",
    "xing2dong4|行动",
    "kai1xin1|开心",
    "dai4lai2|带来",
    "guo4lai2|过来",
    "jia1ting2|家庭",
    "quan2bu4|全部",
    "gang1gang5|刚刚",
    "zheng4chang2|正常",
    "fu2wu4|服务",
    "xiang3dao4|想到",
    "xing2wei2|行为",
    "hao3xiang4|好像",
    "yuan4yi4|愿意",
    "yin1yue4|音乐",
    "gan3xie4|感谢",
    "na4yang4|那样",
    "zhao4pian4|照片",
    "gan3dao4|感到",
    "qing1chu5|清楚",
    "yin2hang2|银行",
    "gu4shi4|故事",
    "yuan2lai2|原来",
    "ta1men5|它们",
    "huan1ying2|欢迎",
    "yi1ban1|一般",
    "ke3ai4|可爱",
    "xin1wen2|新闻",
    "yan3jing5|眼睛",
    "zuo4dao4|做到",
    "zen3yang4|怎样",
    "sheng1yin1|声音",
    "bian4cheng2|变成",
    "shou4dao4|受到",
    "jing1guo4|经过",
    "zhi3neng2|只能",
    "chong2xin1|重新",
    "piao4liang5|漂亮",
    "jing1chang2|经常",
    "mian4qian2|面前",
    "jie2mu4|节目",
    "jian4kang1|健康",
    "zuo4yong4|作用",
    "shuo1ming2|说明",
    "xu3duo1|许多",
    "tong2yang4|同样",
    "shen1bian1|身边",
    "yue4lai2yue4|越来越",
    "yi4si5|意思",
    "yi4jian4|意见",
    "zhu3yao4|主要",
    "bu4shao3|不少",
    "tao3lun4|讨论",
    "chao1guo4|超过",
    "bi3ru2|比如",
    "hou4lai2|后来",
    "zi4you2|自由",
    "jiu4yao4|就要",
    "jia1you2|加油",
    "shi2fen1|十分",
    "nian2qing1|年轻",
    "tiao2jian4|条件",
    "wan3an1|晚安",
    "guang3gao4|广告",
    "ti2chu1|提出",
    "shang4wei4|尚未",
    "di4qiu2|地球",
    "wen2jian4|文件",
    "cheng2xu4|程序",
    "qu3dai4|取代",
    "shi2ji4|实际",
    "wei4neng2|未能",
    "tou2ru4|投入",
    "di4mian4|地面",
    "fa3yuan4|法院",
    "ying1chi3|英尺",
    "zhong1gong4|中共",
    "xiang1guan1|相关",
    "sui2hou4|随后",
    "biao1zhun3|标准",
    "gai4nian4|概念",
    "jian4zao4|建造",
    "xiao4guo3|效果",
    "jing3fang1|警方",
    "she4you3|设有",
    "zhi4zuo4|制作",
    "fang1an4|方案",
    "yue4tai2|月台",
    "nan2zi5|男子",
    "ou1zhou1|欧洲",
    "kai1fa1|开发",
    "yan3chang4|演唱",
    "huang2di4|皇帝",
    "di4xia4|地下",
    "shui3yu4|水域",
    "ju4da4|巨大",
    "kuai4su4|快速",
    "you3xiao4|有效",
    "zhan4dou4|战斗",
    "ren2gong1|人工",
    "da4duo1|大多",
    "ying3pian4|影片",
    "ji2zhong1|集中",
    "fa1biao3|发表",
    "bu4fen4|部份",
    "ge2ming4|革命",
    "qi3ye4|企业",
    "chuan2tong3|传统",
    "wang3luo4|网络",
    "hao2mi3|毫米",
    "dan1wei4|单位",
    "yuan2su4|元素",
    "si1xiang3|思想",
    "shui3ping2|水平",
    "zhi1yuan2|支援",
    "xun4su4|迅速",
    "bei3bu4|北部",
    "mei2ti3|媒体",
    "ju1zhu4|居住",
    "shi4min2|市民",
    "jin4shi4|进士",
    "bi4mian3|避免",
    "jiao4tang2|教堂",
    "ci3hou4|此后",
    "sheng1zhang3|生长",
    "ting2zhi3|停止",
    "an4zhao4|按照",
    "jie1jin4|接近",
    "bao3liu2|保留",
    "chu1qi1|初期",
    "mou3xie1|某些",
    "zhi2wu4|植物",
    "sheng1ya2|生涯",
    "he2ping2|和平",
    "chang4pian4|唱片",
    "he2xin1|核心",
    "zhong1wen2|中文",
    "qu3xiao1|取消",
    "ming2cheng1|名称",
    "li3lun4|理论",
    "ke1xue2|科学",
    "di4wu3|第五",
    "wen2zhang1|文章",
    "bu4zu2|不足",
    "quan2mian4|全面",
    "da4lu4|大陆",
    "shi2xian4|实现",
    "ti2sheng1|提升",
    "cai2liao4|材料",
    "zuo4chu1|作出",
    "nan2bu4|南部",
    "ge4di4|各地",
    "de2yi3|得以",
    "jin4zhi3|禁止",
    "fan3hui2|返回",
    "neng2liang4|能量",
    "gao1zhong1|高中",
    "chu1sheng1|出生",
    "nan2jing1|南京",
    "yi4shu4|艺术",
    "zuo4zhe3|作者",
    "shi2er4|十二",
    "jian4cheng2|建成",
    "de2zhi1|得知",
    "pu3tong1|普通",
    "biao3mian4|表面",
    "fa1bu4|发布",
    "zai4du4|再度",
    "jing4nei4|境内",
    "shi2dai4|时代",
    "fan4wei2|范围",
    "ren4ming4|任命",
    "ji2qi2|及其",
    "zhi2zhi4|直至",
    "xi1fang1|西方",
    "fan3dui4|反对",
    "nian2du4|年度",
    "zhi1xia4|之下",
    "jie2zhi4|截至",
    "yu3yan2|语言",
    "bo1fang4|播放",
    "bai2se4|白色",
    "jiang4di1|降低",
    "gong1min2|公民",
    "ke3da2|可达",
    "shi4bing1|士兵",
    "wan2zheng3|完整",
    "ba1shi4|巴士",
    "pu3bian4|普遍",
    "xian4lu4|线路",
    "bei4jing3|背景",
    "xu1qiu2|需求",
    "ge4zhong3|各种",
    "hai3jun1|海军",
    "zhong1xue2|中学",
    "ju3xing2|举行",
    "zhong4da4|重大",
    "ying4yong4|应用",
    "xi1nan2|西南",
    "yin1su4|因素",
    "te4ding4|特定",
    "feng1ge2|风格",
    "gai3ming2|改名",
    "sen1lin2|森林",
    "wen2zi4|文字",
    "you3zhu4|有著",
    "yan3yuan2|演员",
    "yuan2nian2|元年",
    "chu1kou3|出口",
    "cao1zuo4|操作",
    "mo2xing2|模型",
    "shi2wu4|食物",
    "gong1fen1|公分",
    "gong1ju4|工具",
    "gai3shan4|改善",
];
pub const ZH_HARD: &[&str] = &[
    "jiu4shi4|就是",
    "xu1yao4|需要",
    "kai1shi3|开始",
    "xi1wang4|希望",
    "fa1sheng1|发生",
    "wei4le5|为了",
    "zhi3shi4|只是",
    "shi4jie4|世界",
    "qing2kuang4|情况",
    "bi3sai4|比赛",
    "dan1xin1|担心",
    "ji4xu4|继续",
    "zhi1hou4|之后",
    "guan1xi5|关系",
    "liao3jie3|了解",
    "yi1qie4|一切",
    "ren4he2|任何",
    "jue2ding4|决定",
    "xuan3ze2|选择",
    "zhi3you3|只有",
    "ru2he2|如何",
    "zuo4wei2|作为",
    "qi2shi2|其实",
    "dang1ran2|当然",
    "xiao1xi5|消息",
    "biao3xian4|表现",
    "jie3jue2|解决",
    "zhi1jian1|之间",
    "cheng2gong1|成功",
    "guan1yu2|关于",
    "shen4zhi4|甚至",
    "zhi1qian2|之前",
    "wu2fa3|无法",
    "dui4yu2|对于",
    "jie2shu4|结束",
    "diao4cha2|调查",
    "fang1shi4|方式",
    "mei3yuan2|美元",
    "chu3li3|处理",
    "zheng4fu3|政府",
    "neng2li4|能力",
    "bao3hu4|保护",
    "zhi1chi2|支持",
    "zhu4yi4|注意",
    "xi4tong3|系统",
    "shi4fou3|是否",
    "yi3ji2|以及",
    "zheng3ge4|整个",
    "ji2le5|极了",
    "yan2jiu1|研究",
    "bao3zheng4|保证",
    "gen1ben3|根本",
    "cheng2shi4|城市",
    "mu4qian2|目前",
    "you2xi4|游戏",
    "bi3jiao4|比较",
    "kao3lü4|考虑",
    "cun2zai4|存在",
    "ti2gong1|提供",
    "zhong1yu2|终于",
    "xian4chang3|现场",
    "xia4lai5|下来",
    "ge4ren2|个人",
    "chu2le5|除了",
    "zong3shi4|总是",
    "jing1shen2|精神",
    "dai4biao3|代表",
    "bao3chi2|保持",
    "tu1ran2|突然",
    "li3mian4|里面",
    "que4ding4|确定",
    "mu4biao1|目标",
    "ren4wu5|任务",
    "rong2yi4|容易",
    "lian2xi4|联系",
    "yin1ci3|因此",
    "he2zuo4|合作",
    "ren2yuan2|人员",
    "bao4gao4|报告",
    "zhi4liao2|治疗",
    "gen1ju4|根据",
    "huo4de2|获得",
    "sheng1ming4|生命",
    "ming2xian3|明显",
    "ceng2jing1|曾经",
    "ling4wai4|另外",
    "jian3dan1|简单",
    "dao4di3|到底",
    "jue2dui4|绝对",
    "jian1chi2|坚持",
    "hao3hao3|好好",
    "ji4shu4|技术",
    "she4ji4|设计",
    "wei4lai2|未来",
    "li4yong4|利用",
    "kan4lai5|看来",
    "jian4yi4|建议",
    "yan2zhong4|严重",
    "ge4wei4|各位",
    "bao1kuo4|包括",
    "yi4yi4|意义",
    "fa3lü4|法律",
    "fu4qin1|父亲",
    "bing4qie3|并且",
    "she4hui4|社会",
    "xia4qu4|下去",
    "zheng4ming2|证明",
    "ji4zhe3|记者",
    "que4shi2|确实",
    "bu4guan3|不管",
    "fa1zhan3|发展",
    "zhi4shao3|至少",
    "jie3shi4|解释",
    "fu4ze2|负责",
    "shou3xian1|首先",
    "jiao1yi4|交易",
    "li4shi3|历史",
    "li3jie3|理解",
    "bao4dao4|报道",
    "fu4mu3|父母",
    "zhi1yi1|之一",
    "li4liang5|力量",
    "an1pai2|安排",
    "xiang4mu4|项目",
    "zao4cheng2|造成",
    "ren2sheng1|人生",
    "hui4yi4|会议",
    "xing4fu2|幸福",
    "zi4ran2|自然",
    "ze2ren4|责任",
    "shi1qu4|失去",
    "ren2min2|人民",
    "mian4dui4|面对",
    "shi4jian4|事件",
    "ya1li4|压力",
    "you2yu2|由于",
    "jie2hun1|结婚",
    "mu3qin1|母亲",
    "xun4lian4|训练",
    "tong2yi4|同意",
    "zong3tong3|总统",
    "bu4men2|部门",
    "si4hu1|似乎",
    "ji1hu1|几乎",
    "guo4cheng2|过程",
    "bao3bei4|宝贝",
    "wei4zhi5|位置",
    "fu4jin4|附近",
    "xuan3shou3|选手",
    "can1yu4|参与",
    "reng2ran2|仍然",
    "xian3shi4|显示",
    "er2shi4|而是",
    "shu3yu2|属于",
    "zhi2de5|值得",
    "ren2lei4|人类",
    "shou3shu4|手术",
    "jing1li4|经历",
    "jia1ru4|加入",
    "xiong1di4|兄弟",
    "yu4dao4|遇到",
    "di4zhi3|地址",
    "wu2lun4|无论",
    "jin3zhang1|紧张",
    "shi4shi2|事实",
    "ben3lai2|本来",
    "ji1ben3|基本",
    "zhuan1jia1|专家",
    "yi3lai2|以来",
    "fan3ying4|反应",
    "di4qu1|地区",
    "guan1zhu4|关注",
    "biao3yan3|表演",
    "jing3cha2|警察",
    "zi1liao4|资料",
    "jia4zhi2|价值",
    "xiang1dang1|相当",
    "kun4nan5|困难",
    "zhuan1ye4|专业",
    "nan2dao4|难道",
    "yu2shi4|于是",
    "gui1ding4|规定",
    "chan3sheng1|产生",
    "dui4fang1|对方",
    "zhuang4tai4|状态",
    "xin1li3|心理",
    "huan2jing4|环境",
    "jian4li4|建立",
    "ting2xia4|停下",
    "geng4jia1|更加",
    "lao3ban3|老板",
    "qi1zi3|妻子",
    "shi4chang3|市场",
    "bi4yao4|必要",
    "wei1xian3|危险",
    "qin1ai4|亲爱",
    "guan3li3|管理",
    "shi4he2|适合",
    "zheng4shi4|正式",
    "yin3qi3|引起",
    "mi4mi4|秘密",
    "ling3dao3|领导",
    "hei1se4|黑色",
    "deng3deng3|等等",
    "cong2er2|从而",
    "yi1ran2|依然",
    "bian4hua4|变化",
    "lei4si4|类似",
    "biao3ming2|表明",
    "she4bei4|设备",
    "yun4xing2|运行",
    "gong1bu4|公布",
    "chuang4zuo4|创作",
    "ji1chu3|基础",
    "chong2jian4|重建",
    "ping2tai2|平台",
    "dong1jing1|东京",
    "fen4zi3|分子",
    "jie1dao4|街道",
    "xi1bu4|西部",
    "sui2zhe5|随着",
    "er4shi2|二十",
    "yue4nan2|越南",
    "dan1qu1|单曲",
    "cuo4shi1|措施",
    "ben3di4|本地",
    "mei3ge4|每个",
    "liu2xia4|留下",
    "shang4ying4|上映",
    "zhu3chi2|主持",
    "shu1ji4|书记",
    "zuo4jia1|作家",
    "gong1lu4|公路",
    "fen1bu4|分布",
    "xing2xiang4|形象",
    "geng1ming2|更名",
    "liu2xing2|流行",
    "yi2min2|移民",
    "zhu2jian4|逐渐",
    "lü3ke4|旅客",
    "li4ji2|立即",
    "chan3pin3|产品",
    "ju3ban4|举办",
    "she4li4|设立",
    "cheng2ke4|乘客",
    "gong1yuan2|公园",
    "gai3zao4|改造",
    "man4hua4|漫画",
    "xian4dai4|现代",
    "ji4lu4|纪录",
    "xi1bei3|西北",
    "shang4shu4|上述",
    "zai1pei2|栽培",
    "zi4shen1|自身",
    "zhong1hua2|中华",
    "fen1wei2|分为",
    "fu2he2|符合",
    "xin4yang3|信仰",
    "xiu1gai3|修改",
    "nei4bu4|内部",
    "dong4hua4|动画",
    "ru2xia4|如下",
    "guang3chang3|广场",
    "pei4he2|配合",
    "xi1yin3|吸引",
    "wang3wang3|往往",
    "shou1ru4|收入",
    "wen2xue2|文学",
    "ge1shou3|歌手",
    "di4liu4|第六",
    "shi4gu4|事故",
    "zhu4zuo4|著作",
    "sui2zhu4|随著",
    "ti2dao4|提到",
    "su1lian2|苏联",
    "yi1tong2|一同",
    "nan2fang1|南方",
    "gu4ding4|固定",
    "shi4wei4|视为",
    "tou4guo4|透过",
    "jiao1liu2|交流",
    "wei3yuan2|委员",
    "zhi3ding4|指定",
    "po4huai4|破坏",
    "bu4luo4|部落",
    "zu3zhi3|阻止",
    "shang1ye4|商业",
    "yu3zhou4|宇宙",
    "liu2yu4|流域",
    "er2yan2|而言",
    "xuan3ju3|选举",
    "bao3cun2|保存",
    "che1liang4|车辆",
    "gong1zhu3|公主",
    "ji1yin1|基因",
    "qiu2dui4|球队",
    "lian2jie1|连接",
    "bing4mei2|并没",
    "ba1li2|巴黎",
    "yong4hu4|用户",
];
pub const ZH_EXPERT: &[&str] = &[
    "wei2yi1|唯一",
    "ru2ci3|如此",
    "ken3ding4|肯定",
    "you3guan1|有关",
    "kong4zhi4|控制",
    "zu3zhi1|组织",
    "yong1you3|拥有",
    "zui4zhong1|最终",
    "bu4zai4|不再",
    "si3wang2|死亡",
    "zai4ci4|再次",
    "fang4qi4|放弃",
    "ji2shi3|即使",
    "jin3guan3|尽管",
    "tou2piao4|投票",
    "ke4hu4|客户",
    "ju1ran2|居然",
    "fen1xi1|分析",
    "xiang3shou4|享受",
    "fan4zui4|犯罪",
    "guan1jian4|关键",
    "guan4jun1|冠军",
    "hui1fu4|恢复",
    "tong2zhi4|同志",
    "yi4shi2|意识",
    "yi1dan4|一旦",
    "zhi2xing2|执行",
    "fen1xiang3|分享",
    "er2yi3|而已",
    "nü3xing4|女性",
    "zhi1lei4|之类",
    "tao3yan4|讨厌",
    "ren2wu4|人物",
    "ju4jue2|拒绝",
    "dui4wu3|队伍",
    "bu4zhi1|不知",
    "ying1xiong2|英雄",
    "xie2yi4|协议",
    "wei1xie2|威胁",
    "gong1ji1|攻击",
    "jing4zheng1|竞争",
    "gu1ji4|估计",
    "yi4wei4zhe5|意味着",
    "ju4le4bu4|俱乐部",
    "yun3xu3|允许",
    "cuo4guo4|错过",
    "suo3wei4|所谓",
    "an4jian4|案件",
    "zhi1zhong1|之中",
    "kong3bu4|恐怖",
    "zi4wo3|自我",
    "jian4zhu4|建筑",
    "feng1kuang2|疯狂",
    "wei3yuan2hui4|委员会",
    "you3suo3|有所",
    "yao1qing3|邀请",
    "jia1shang4|加上",
    "pai1she4|拍摄",
    "qu1yu4|区域",
    "nan2yi3|难以",
    "shuo1shi2hua4|说实话",
    "shi2shang4|时尚",
    "jia1huo5|家伙",
    "bao4zha4|爆炸",
    "zhan3shi4|展示",
    "ji1di4|基地",
    "qing2xu4|情绪",
    "zhang3wo4|掌握",
    "zui4jia1|最佳",
    "ji4yi4|记忆",
    "sheng4xia4|剩下",
    "jun1dui4|军队",
    "ji1jin1|基金",
    "she4qu1|社区",
    "shou3duan4|手段",
    "xue2hui4|学会",
    "yi2han4|遗憾",
    "bu4dui4|部队",
    "jie1chu4|接触",
    "cong1ming5|聪明",
    "pi2fu1|皮肤",
    "li4hai5|厉害",
    "zun1zhong4|尊重",
    "sun3shi1|损失",
    "ke3lian2|可怜",
    "wei4he2|为何",
    "zhong1yang1|中央",
    "xi2ji1|袭击",
    "cheng2nuo4|承诺",
    "gan3ran3|感染",
    "qi3dong4|启动",
    "nian2ling2|年龄",
    "yi1yi1|一一",
    "suan4shi4|算是",
    "ke3xi1|可惜",
    "hui2yi4|回忆",
    "hun1yin1|婚姻",
    "da3ji1|打击",
    "zhi1wai4|之外",
    "shu2xi1|熟悉",
    "shi2qi1|时期",
    "hao3yun4|好运",
    "sheng1wu4|生物",
    "ren2shi4|人士",
    "ji2tuan2|集团",
    "wei2zhi3|为止",
    "bi3ci3|彼此",
    "tui1jian4|推荐",
    "pin3pai2|品牌",
    "shi4pin2|视频",
    "zhen1xiang4|真相",
    "zan4shi2|暂时",
    "jing1xi3|惊喜",
    "you3zhe5|有着",
    "bing4du2|病毒",
    "quan2li4|权力",
    "hao2wu2|毫无",
    "chang2shi4|尝试",
    "ji2bing4|疾病",
    "zi3xi4|仔细",
    "yu2le4|娱乐",
    "ming4ling4|命令",
    "xin1shang3|欣赏",
    "zheng4ce4|政策",
    "shen2jing1|神经",
    "gao1du4|高度",
    "fa3ting2|法庭",
    "yi1bei4zi5|一辈子",
    "quan2shi4jie4|全世界",
    "lian2meng2|联盟",
    "shuo1fa3|说法",
    "ping2lun4|评论",
    "wu4zhi4|物质",
    "yi2shi4|仪式",
    "neng2fou3|能否",
    "jin4gong1|进攻",
    "zai4shuo1|再说",
    "you2qi2|尤其",
    "bing4fei1|并非",
    "fei1fa3|非法",
    "ben3shen1|本身",
    "shang4di4|上帝",
    "shi2guang1|时光",
    "bu4jian4|不见",
    "bo2shi4|博士",
    "huo4shi4|或是",
    "lang4man4|浪漫",
    "qiu2yuan2|球员",
    "dao4de2|道德",
    "bian1ji2|编辑",
    "si1ren2|私人",
    "xin1ku3|辛苦",
    "zheng4shi2|证实",
    "yi1lu4|一路",
    "yao4me5|要么",
    "ling3yu4|领域",
    "jiang1jun1|将军",
    "tou4lu4|透露",
    "bi4jing4|毕竟",
    "gong1xi3|恭喜",
    "shi1ti3|尸体",
    "lian4ai4|恋爱",
    "tuan2dui4|团队",
    "zhi3bu5guo4|只不过",
    "ge1qu3|歌曲",
    "mo2shi4|模式",
    "yi4chang2|异常",
    "dang4an4|档案",
    "xie2hui4|协会",
    "xi4bao1|细胞",
    "yi1mian4|一面",
    "zheng4zhuang4|症状",
    "shi4tu2|试图",
    "huan4zhe3|患者",
    "bo1li5|玻璃",
    "jun1shi4|军事",
    "fen3si1|粉丝",
    "zhi4yu2|至于",
    "suo3zai4|所在",
    "ling2hun2|灵魂",
    "dai4kuan3|贷款",
    "que1fa2|缺乏",
    "ling2chen2|凌晨",
    "ta1ren2|他人",
    "tao2tai4|淘汰",
    "gong1zhong4|公众",
    "shi4fang4|释放",
    "huo4sheng4|获胜",
    "da2cheng2|达成",
    "gu3li4|鼓励",
    "dan4gao1|蛋糕",
    "ben3ren2|本人",
    "xin1zang4|心脏",
    "hou4hui3|后悔",
    "dou4zheng1|斗争",
    "jia1zu2|家族",
    "mei4li4|魅力",
    "ji3yu3|给予",
    "wu3dao3|舞蹈",
    "tu1po4|突破",
    "pi1zhun3|批准",
    "kong1jian1|空间",
    "xian4ru4|陷入",
    "ti3zhang3|体长",
    "yi2du4|一度",
    "hu4xiang1|互相",
    "xie2zhu4|协助",
    "gong1ye4|工业",
    "she4ji2|涉及",
    "xiang1si4|相似",
    "gui1mo2|规模",
    "bing4yu2|并于",
    "chi2xu4|持续",
    "te4se4|特色",
    "lei4xing2|类型",
    "yi2zhi4|一致",
    "zhu3jiao4|主教",
    "da4chen2|大臣",
    "dian4zi5|电子",
    "di4qi1|第七",
    "gui1hua4|规划",
    "bei3fang1|北方",
    "yin3qing2|引擎",
    "you3xian4|有限",
    "shen1du4|深度",
    "huang2jia1|皇家",
    "tong1dao4|通道",
    "ding4yi4|定义",
    "fa3an4|法案",
    "zhi4zao4|制造",
    "cheng2ben3|成本",
    "yi4hui4|议会",
    "sui4dao4|隧道",
    "tuan2ti3|团体",
    "da4yue1|大约",
    "dong1nan2|东南",
    "tong3yi1|统一",
    "dong1bei3|东北",
    "yi3wai4|以外",
    "li4yi4|利益",
    "gu3dai4|古代",
    "ming2wei4|名为",
    "guang3fan4|广泛",
    "gai3wei2|改为",
    "wu4li3|物理",
    "te4zheng1|特征",
    "yi4yuan2|议员",
    "guo2wang2|国王",
    "xue2zhe3|学者",
    "kai1fang4|开放",
    "hai3wai4|海外",
    "zhe4shi4|这是",
    "jin1ri4|今日",
    "xian1hou4|先后",
    "chu1ren4|出任",
    "bu4de2|不得",
    "you4ming2|又名",
    "gong1ren2|工人",
    "min2guo2|民国",
    "he2bing4|合并",
    "xia4jiang4|下降",
    "shao4nian2|少年",
    "qi1xi1|栖息",
    "xiao3shuo1|小说",
    "yin3zhong3|引种",
    "zhi3hui1|指挥",
    "ao4men2|澳门",
    "fu2jian4|福建",
    "shi4shi4|逝世",
    "yuan2shi3|原始",
    "da4xiao3|大小",
    "zi4mu3|字母",
    "jia1zhong1|家中",
    "zuo3you4|左右",
    "da3suan4|打算",
    "chai1chu2|拆除",
    "chao2ting2|朝廷",
    "jia1jing4|嘉靖",
    "chang2chang2|常常",
    "guang3bo1|广播",
    "fang1bian4|方便",
    "xiao1shi1|消失",
    "ji4zai3|记载",
    "she4zhi4|设置",
    "bu4duan4|不断",
    "fang2wu1|房屋",
    "chao2xian1|朝鲜",
    "bi4ye4|毕业",
    "zhong1bu4|中部",
    "ge4zi4|各自",
    "wai4jiao1|外交",
    "lian2sai4|联赛",
    "wu3tai2|舞台",
    "liang2hao3|良好",
    "gong1kai1|公开",
    "yuan2ming2|原名",
    "ji1yu2|基于",
    "tian1jin1|天津",
    "xing4neng2|性能",
    "bing4zai4|并在",
];

pub fn zh_tier(tier: &str) -> &'static [&'static str] {
    match tier {
        "easy" => ZH_EASY,
        "medium" => ZH_MEDIUM,
        "hard" => ZH_HARD,
        "expert" => ZH_EXPERT,
        _ => ZH_MEDIUM,
    }
}

/// Word bank for a built-in language + tier (English by default).
pub fn tier_for(lang: &str, tier: &str) -> &'static [&'static str] {
    use crate::consts::{AR, DE, ES, FA, FIL, FR, HI, JA, KO, PL, PT, RU, UR, VI, ZH};
    match lang {
        // CC-LINEUP-SWAP registered these four; their content is
        // CC-NEW-LANG-CONTENT's scope and has not landed. They return an EMPTY
        // bank rather than falling through to `en_tier` below — a registered
        // language with no content must serve NO words, never English words
        // wearing its name. Silent English fallback is how you ship "Russian"
        // that spells "bed"; the keyboard charset test catches it precisely
        // because this arm is explicit.
        RU | AR | FA | UR | HI => audit_draft_or_empty(lang, tier),
        ES => es_tier(tier),
        FR => simple_tier(FR_EASY, FR_MEDIUM, FR_HARD, FR_EXPERT, tier),
        DE => simple_tier(DE_EASY, DE_MEDIUM, DE_HARD, DE_EXPERT, tier),
        PT => simple_tier(PT_EASY, PT_MEDIUM, PT_HARD, PT_EXPERT, tier),
        PL => simple_tier(PL_EASY, PL_MEDIUM, PL_HARD, PL_EXPERT, tier),
        VI => simple_tier(VI_EASY, VI_MEDIUM, VI_HARD, VI_EXPERT, tier),
        KO => simple_tier(KO_EASY, KO_MEDIUM, KO_HARD, KO_EXPERT, tier),
        JA => simple_tier(JA_EASY, JA_MEDIUM, JA_HARD, JA_EXPERT, tier),
        FIL => simple_tier(FIL_EASY, FIL_MEDIUM, FIL_HARD, FIL_EXPERT, tier),
        ZH => zh_tier(tier),
        _ => en_tier(tier),
    }
}

/// ru/ar/fa/ur have no verified content. In production they serve NOTHING (an
/// empty bank, never English words wearing their name — the whole point of the
/// explicit arm). Under `audit_preview` ONLY, they serve their unverified DRAFT
/// bank so a native speaker can play and review it. Two cfg'd definitions so the
/// production binary contains only the empty one.
#[cfg(feature = "audit_preview")]
fn audit_draft_or_empty(lang: &str, tier: &str) -> &'static [&'static str] {
    crate::word_data_audit::tier_for(lang, tier)
}
#[cfg(not(feature = "audit_preview"))]
fn audit_draft_or_empty(_lang: &str, _tier: &str) -> &'static [&'static str] {
    &[]
}

#[cfg(test)]
mod content_tests {
    use crate::consts::{TIER_ORDER, AR, FA, RU, UR};

    /// A language registered WITHOUT content must serve nothing — never English
    /// words under its own name. `tier_for` ends in `_ => en_tier(tier)`, so any
    /// new registry entry silently inherits the English bank until someone adds
    /// an explicit arm; this test is the tripwire for that.
    ///
    /// Guarded to the PRODUCTION config: the audit-preview build deliberately fills
    /// these with draft banks (asserted separately below), so the "serves nothing"
    /// invariant is exactly a not-audit_preview property.
    #[cfg(not(feature = "audit_preview"))]
    #[test]
    fn registered_but_contentless_languages_serve_no_words() {
        for lang in [RU, AR, FA, UR] {
            for tier in TIER_ORDER {
                let bank = super::tier_for(lang, tier);
                assert!(
                    bank.is_empty(),
                    "{lang}/{tier} must be empty until its content lands, got {} words starting {:?} \
                     — a fallthrough to en_tier would serve English words as {lang}",
                    bank.len(),
                    bank.first(),
                );
            }
        }
    }

    /// The mirror invariant for the audit build: those same languages now serve
    /// their DRAFT banks (non-empty), so an auditor has words to play.
    #[cfg(feature = "audit_preview")]
    #[test]
    fn audit_preview_serves_draft_banks() {
        for lang in [RU, AR, FA, UR] {
            for tier in TIER_ORDER {
                assert!(
                    !super::tier_for(lang, tier).is_empty(),
                    "audit_preview: {lang}/{tier} should serve its draft bank"
                );
            }
        }
    }

    /// The languages that DO have content still have it (guards against an
    /// over-broad empty arm swallowing a real bank).
    #[test]
    fn content_languages_still_have_banks() {
        for lang in ["en", "es", "fr", "de", "pt", "pl", "vi", "ko", "ja", "fil", "zh"] {
            for tier in TIER_ORDER {
                assert!(!super::tier_for(lang, tier).is_empty(), "{lang}/{tier} lost its bank");
            }
        }
    }
}

#[cfg(test)]
mod tier_dump {
    //! Read-only diagnostic support: dump exactly what `tier_for` ships, for the
    //! tier-health report. Ignored by default; run explicitly:
    //!   cargo test --lib tier_dump::dump -- --ignored --nocapture
    use crate::consts::BUILTIN_LANGS;

    #[test]
    #[ignore]
    fn dump() {
        let tiers = ["easy", "medium", "hard", "expert"];
        let mut obj = String::from("{\n");
        for (li, (lang, _, _, _)) in BUILTIN_LANGS.iter().enumerate() {
            obj.push_str(&format!("  \"{lang}\": {{\n"));
            for (ti, tier) in tiers.iter().enumerate() {
                let words = super::tier_for(lang, tier);
                let items: Vec<String> = words
                    .iter()
                    // raw UTF-8, JSON-escape only " and \ (keep CJK scripts literal)
                    .map(|w| format!("\"{}\"", w.replace('\\', "\\\\").replace('"', "\\\"")))
                    .collect();
                let comma = if ti + 1 < tiers.len() { "," } else { "" };
                obj.push_str(&format!("    \"{tier}\": [{}]{comma}\n", items.join(", ")));
            }
            let comma = if li + 1 < BUILTIN_LANGS.len() { "," } else { "" };
            obj.push_str(&format!("  }}{comma}\n"));
        }
        obj.push_str("}\n");
        std::fs::write("tools/tierhealth/tiers_dump.json", obj).expect("write dump");
        eprintln!("wrote tools/tierhealth/tiers_dump.json");
    }
}
