//! `LANGUAGES` is used only for the "Speak in" voice picker in the Import
//! ("My Words") modal. The built-in word banks that back normal play live in
//! `word_data.rs` — a @generated file produced by `scripts/build-wordlists.py`
//! from the curated sources in `assets/words/{code}/{tier}.txt` (edit those and
//! re-run the pipeline; never edit `word_data.rs` by hand). Their audio is
//! fetched from the backend's `/api/speak`.

use crate::word_data::*;

pub struct LangInfo {
    pub name: &'static str,
    pub code: &'static str,
}

pub const LANGUAGES: [(&str, LangInfo); 20] = [
    ("en", LangInfo { name: "English", code: "en-US" }),
    ("es", LangInfo { name: "Espa\u{f1}ol", code: "es-ES" }),
    ("fr", LangInfo { name: "Fran\u{e7}ais", code: "fr-FR" }),
    ("de", LangInfo { name: "Deutsch", code: "de-DE" }),
    ("pt", LangInfo { name: "Portugu\u{ea}s", code: "pt-BR" }),
    ("pl", LangInfo { name: "Polski", code: "pl-PL" }),
    ("tr", LangInfo { name: "T\u{fc}rk\u{e7}e", code: "tr-TR" }),
    // CC-LINEUP-SWAP D3 variants: Russian standard ru-RU; Modern Standard
    // Arabic; Iranian Persian (fa-IR, not Dari); Urdu ur-PK standard. Audio is
    // direction-agnostic, so the three RTL languages carry voices here even
    // though the rtl_required gate keeps them off every playable surface.
    ("ru", LangInfo { name: "\u{420}\u{443}\u{441}\u{441}\u{43a}\u{438}\u{439}", code: "ru-RU" }),
    ("ar", LangInfo { name: "\u{627}\u{644}\u{639}\u{631}\u{628}\u{64a}\u{629}", code: "ar-SA" }),
    ("fa", LangInfo { name: "\u{641}\u{627}\u{631}\u{633}\u{6cc}", code: "fa-IR" }),
    ("ur", LangInfo { name: "\u{627}\u{631}\u{62f}\u{648}", code: "ur-PK" }),
    // New languages with their own keyboard + backend voice (My Words matches).
    ("vi", LangInfo { name: "Ti\u{1ebf}ng Vi\u{1ec7}t", code: "vi-VN" }),
    ("ko", LangInfo { name: "\u{d55c}\u{ad6d}\u{c5b4}", code: "ko-KR" }),
    ("ja", LangInfo { name: "\u{65e5}\u{672c}\u{8a9e}", code: "ja-JP" }),
    ("th", LangInfo { name: "\u{e44}\u{e17}\u{e22}", code: "th-TH" }),
    ("fil", LangInfo { name: "Filipino", code: "fil-PH" }),
    // Mandarin: native audio for imported hanzi (the pinyin keyboard can't type
    // arbitrary hanzi, so My Words Chinese keeps the English layout).
    ("zh", LangInfo { name: "\u{4e2d}\u{6587}", code: "cmn-CN" }),
    ("ro", LangInfo { name: "Rom\u{e2}n\u{103}", code: "ro-RO" }),
    ("id", LangInfo { name: "Indonesia", code: "id-ID" }),
    ("ca", LangInfo { name: "Catal\u{e0}", code: "ca-ES" }),
];

pub fn en_tier(tier: &str) -> &'static [&'static str] {
    match tier {
        "easy" => EN_EASY,
        "medium" => EN_MEDIUM,
        "hard" => EN_HARD,
        "expert" => EN_EXPERT,
        _ => EN_MEDIUM,
    }
}

pub fn es_tier(tier: &str) -> &'static [&'static str] {
    match tier {
        "easy" => ES_EASY,
        "medium" => ES_MEDIUM,
        "hard" => ES_HARD,
        "expert" => ES_EXPERT,
        _ => ES_MEDIUM,
    }
}

fn simple_tier(easy: &'static [&'static str], medium: &'static [&'static str], hard: &'static [&'static str], expert: &'static [&'static str], tier: &str) -> &'static [&'static str] {
    match tier {
        "easy" => easy,
        "medium" => medium,
        "hard" => hard,
        "expert" => expert,
        _ => medium,
    }
}

// Mandarin: entries are "pinyin|hanzi" — the pinyin (before '|') is the typed
// answer, the hanzi (after '|') is what TTS speaks + what's revealed. Hand-
// curated small set (2-syllable to avoid homophone ambiguity); native review
// flagged. Not run through the pipeline (its charset gate is for single-string
// words); the keyboard charset test validates the pinyin side separately.
pub const ZH_EASY: &[&str] = &[
    "wo3men5|我们",
    "mei2you3|没有",
    "ta1men5|他们",
    "shen2me5|什么",
    "xian4zai4|现在",
    "zhi1dao4|知道",
    "shi2hou5|时候",
    "gong1zuo4|工作",
    "ni3men5|你们",
    "shi2jian1|时间",
    "zen3me5|怎么",
    "zhe4xie1|这些",
    "xi3huan5|喜欢",
    "hai2you3|还有",
    "jin1tian1|今天",
    "hai2shi5|还是",
    "jue2de5|觉得",
    "kan4dao4|看到",
    "yi1qi3|一起",
    "qi3lai5|起来",
    "yi1xie1|一些",
    "zhao3dao4|找到",
    "fei1chang2|非常",
    "hai2zi5|孩子",
    "zhe4li3|这里",
    "dong1xi1|东西",
    "yi1yang4|一样",
    "zhong4yao4|重要",
    "gao4su4|告诉",
    "di4fang1|地方",
    "chu1lai2|出来",
    "zui4hou4|最后",
    "peng2you5|朋友",
    "de2dao4|得到",
    "na4xie1|那些",
    "zhun3bei4|准备",
    "guo2jia1|国家",
    "dian4hua4|电话",
    "nü3ren2|女人",
    "xiao3shi2|小时",
    "you3xie1|有些",
    "bie2ren5|别人",
    "nan2ren2|男人",
    "zheng4zai4|正在",
    "xue2xiao4|学校",
    "shen1shang5|身上",
    "ren4shi5|认识",
    "ming2tian1|明天",
    "hui2lai5|回来",
    "wan3shang5|晚上",
    "xie4xie5|谢谢",
    "duo1shao3|多少",
    "ma1ma5|妈妈",
    "di4er4|第二",
    "bie2de5|别的",
    "dian4ying3|电影",
    "hui2jia1|回家",
    "zuo2tian1|昨天",
    "xian1sheng5|先生",
    "yi1yuan4|医院",
    "zhen1de5|真的",
    "xue2sheng5|学生",
    "er2zi5|儿子",
    "ming2bai5|明白",
    "ji4de5|记得",
    "zhong1guo2|中国",
    "shen1ti3|身体",
    "na3li3|哪里",
    "na4li5|那里",
    "jie4shao4|介绍",
    "dian4shi4|电视",
    "xia4wu3|下午",
    "chu1qu4|出去",
    "xue2xi2|学习",
    "lao3shi1|老师",
    "da4xue2|大学",
    "yi1sheng1|医生",
    "ming2zi5|名字",
    "ta1men5|她们",
    "ma3shang4|马上",
    "jin1nian2|今年",
    "shou3ji1|手机",
    "kan4jian4|看见",
    "ting1dao4|听到",
    "nü3er2|女儿",
    "shuo1hua4|说话",
    "qi4che1|汽车",
    "ba4ba5|爸爸",
    "gao1xing4|高兴",
    "qu4nian2|去年",
    "lai2dao4|来到",
    "shui4jiao4|睡觉",
    "dian4nao3|电脑",
    "hui2dao4|回到",
    "jia1li3|家里",
    "bu4yong4|不用",
    "ren4zhen1|认真",
    "fang2zi5|房子",
    "fei1ji1|飞机",
    "zao3shang5|早上",
    "hui2da2|回答",
    "hui2qu5|回去",
    "da3kai1|打开",
    "bing4ren2|病人",
    "da3dian4hua4|打电话",
    "xiu1xi5|休息",
    "yi1bian1|一边",
    "you3de5|有的",
    "wang4ji4|忘记",
    "fang2jian1|房间",
    "chi1fan4|吃饭",
    "dong4zuo4|动作",
    "yi1fu5|衣服",
    "shang4ban1|上班",
    "sheng1ri4|生日",
    "jie3jie5|姐姐",
    "yi1ban4|一半",
    "jia1ren2|家人",
    "you3shi2|有时",
    "xiao3jie5|小姐",
    "dui4bu5qi3|对不起",
    "jin4qu4|进去",
    "ge1ge5|哥哥",
    "mei2shen2me5|没什么",
    "lu4shang5|路上",
    "tian1qi4|天气",
    "zui4hao3|最好",
    "kao3shi4|考试",
    "you3shi2hou5|有时候",
    "pang2bian1|旁边",
    "tong2xue2|同学",
    "bang1mang2|帮忙",
    "jin4lai2|进来",
    "jian4mian4|见面",
    "hao3kan4|好看",
    "zhong1jian1|中间",
    "nü3sheng1|女生",
    "di4dian3|地点",
    "xing1qi1|星期",
    "che1shang4|车上",
    "mei4mei5|妹妹",
    "sheng1qi4|生气",
    "di4shang5|地上",
    "shang4wu3|上午",
    "yi1hui4r5|一会儿",
    "ji4zhu5|记住",
    "xia4ci4|下次",
    "zhi1shi5|知识",
    "ji1chang3|机场",
    "xue2yuan4|学院",
];
pub const ZH_MEDIUM: &[&str] = &[
    "zi4ji3|自己",
    "ke3yi3|可以",
    "yi3jing1|已经",
    "zhe4yang4|这样",
    "ru2guo3|如果",
    "yin1wei4|因为",
    "wen4ti2|问题",
    "dan4shi4|但是",
    "ke3neng2|可能",
    "suo3yi3|所以",
    "na4me5|那么",
    "zhe4me5|这么",
    "ren4wei2|认为",
    "ying1gai1|应该",
    "da4jia1|大家",
    "fa1xian4|发现",
    "yi1ding4|一定",
    "yi1zhi2|一直",
    "sheng1huo2|生活",
    "bu4guo4|不过",
    "gong1si1|公司",
    "bu4yao4|不要",
    "suo3you3|所有",
    "er2qie3|而且",
    "bi4xu1|必须",
    "cheng2wei2|成为",
    "qi2ta1|其他",
    "shi4qing5|事情",
    "gan3jue2|感觉",
    "ran2hou4|然后",
    "wei4shen2me5|为什么",
    "jin4xing2|进行",
    "chu1xian4|出现",
    "jian4dao4|见到",
    "tong1guo4|通过",
    "guo4qu4|过去",
    "can1jia1|参加",
    "an1quan2|安全",
    "jie1guo3|结果",
    "huo4zhe3|或者",
    "bu4cuo4|不错",
    "ji1hui4|机会",
    "wan2quan2|完全",
    "ji4hua4|计划",
    "ke3shi4|可是",
    "yi3hou4|以后",
    "yao1qiu2|要求",
    "xiang1xin4|相信",
    "sui1ran2|虽然",
    "yuan2yin1|原因",
    "zhi3yao4|只要",
    "jin4ru4|进入",
    "bu4tong2|不同",
    "you3ren2|有人",
    "fen1zhong1|分钟",
    "jie1shou4|接受",
    "qi2zhong1|其中",
    "ren2men5|人们",
    "neng2gou4|能够",
    "wan2cheng2|完成",
    "bang1zhu4|帮助",
    "nu3li4|努力",
    "dang1shi2|当时",
    "bu4fen5|部分",
    "yi3qian2|以前",
    "ban4fa3|办法",
    "te4bie2|特别",
    "zhen1zheng4|真正",
    "gai3bian4|改变",
    "li2kai1|离开",
    "tong2shi2|同时",
    "yi3wei2|以为",
    "fang1fa3|方法",
    "zhi2jie1|直接",
    "ying3xiang3|影响",
    "yong3yuan3|永远",
    "ye3xu3|也许",
    "fang1mian4|方面",
    "huo2dong4|活动",
    "xin4xi1|信息",
    "zui4jin4|最近",
    "kuai4le4|快乐",
    "shi3yong4|使用",
    "lai2zi4|来自",
    "jian3cha2|检查",
    "zhong1xin1|中心",
    "xing2dong4|行动",
    "kai1xin1|开心",
    "dai4lai2|带来",
    "guo4lai2|过来",
    "jia1ting2|家庭",
    "quan2bu4|全部",
    "gang1gang5|刚刚",
    "zheng4chang2|正常",
    "fu2wu4|服务",
    "xiang3dao4|想到",
    "xing2wei2|行为",
    "hao3xiang4|好像",
    "yuan4yi4|愿意",
    "yin1yue4|音乐",
    "gan3xie4|感谢",
    "na4yang4|那样",
    "zhao4pian4|照片",
    "gan3dao4|感到",
    "qing1chu5|清楚",
    "yin2hang2|银行",
    "gu4shi4|故事",
    "yuan2lai2|原来",
    "ta1men5|它们",
    "huan1ying2|欢迎",
    "yi1ban1|一般",
    "ke3ai4|可爱",
    "xin1wen2|新闻",
    "yan3jing5|眼睛",
    "zuo4dao4|做到",
    "zen3yang4|怎样",
    "sheng1yin1|声音",
    "bian4cheng2|变成",
    "shou4dao4|受到",
    "jing1guo4|经过",
    "zhi3neng2|只能",
    "chong2xin1|重新",
    "piao4liang5|漂亮",
    "jing1chang2|经常",
    "mian4qian2|面前",
    "jie2mu4|节目",
    "jian4kang1|健康",
    "zuo4yong4|作用",
    "shuo1ming2|说明",
    "xu3duo1|许多",
    "tong2yang4|同样",
    "shen1bian1|身边",
    "yue4lai2yue4|越来越",
    "yi4si5|意思",
    "yi4jian4|意见",
    "zhu3yao4|主要",
    "bu4shao3|不少",
    "tao3lun4|讨论",
    "chao1guo4|超过",
    "bi3ru2|比如",
    "hou4lai2|后来",
    "zi4you2|自由",
    "jiu4yao4|就要",
    "jia1you2|加油",
    "shi2fen1|十分",
    "nian2qing1|年轻",
    "tiao2jian4|条件",
    "wan3an1|晚安",
    "guang3gao4|广告",
    "ti2chu1|提出",
];
pub const ZH_HARD: &[&str] = &[
    "jiu4shi4|就是",
    "xu1yao4|需要",
    "kai1shi3|开始",
    "xi1wang4|希望",
    "fa1sheng1|发生",
    "wei4le5|为了",
    "zhi3shi4|只是",
    "shi4jie4|世界",
    "qing2kuang4|情况",
    "bi3sai4|比赛",
    "dan1xin1|担心",
    "ji4xu4|继续",
    "zhi1hou4|之后",
    "guan1xi5|关系",
    "liao3jie3|了解",
    "yi1qie4|一切",
    "ren4he2|任何",
    "jue2ding4|决定",
    "xuan3ze2|选择",
    "zhi3you3|只有",
    "ru2he2|如何",
    "zuo4wei2|作为",
    "qi2shi2|其实",
    "dang1ran2|当然",
    "xiao1xi5|消息",
    "biao3xian4|表现",
    "jie3jue2|解决",
    "zhi1jian1|之间",
    "cheng2gong1|成功",
    "guan1yu2|关于",
    "shen4zhi4|甚至",
    "zhi1qian2|之前",
    "wu2fa3|无法",
    "dui4yu2|对于",
    "jie2shu4|结束",
    "diao4cha2|调查",
    "fang1shi4|方式",
    "mei3yuan2|美元",
    "chu3li3|处理",
    "zheng4fu3|政府",
    "neng2li4|能力",
    "bao3hu4|保护",
    "zhi1chi2|支持",
    "zhu4yi4|注意",
    "xi4tong3|系统",
    "shi4fou3|是否",
    "yi3ji2|以及",
    "zheng3ge4|整个",
    "ji2le5|极了",
    "yan2jiu1|研究",
    "bao3zheng4|保证",
    "gen1ben3|根本",
    "cheng2shi4|城市",
    "mu4qian2|目前",
    "you2xi4|游戏",
    "bi3jiao4|比较",
    "kao3lü4|考虑",
    "cun2zai4|存在",
    "ti2gong1|提供",
    "zhong1yu2|终于",
    "xian4chang3|现场",
    "xia4lai5|下来",
    "ge4ren2|个人",
    "chu2le5|除了",
    "zong3shi4|总是",
    "jing1shen2|精神",
    "dai4biao3|代表",
    "bao3chi2|保持",
    "tu1ran2|突然",
    "li3mian4|里面",
    "que4ding4|确定",
    "mu4biao1|目标",
    "ren4wu5|任务",
    "rong2yi4|容易",
    "lian2xi4|联系",
    "yin1ci3|因此",
    "he2zuo4|合作",
    "ren2yuan2|人员",
    "bao4gao4|报告",
    "zhi4liao2|治疗",
    "gen1ju4|根据",
    "huo4de2|获得",
    "sheng1ming4|生命",
    "ming2xian3|明显",
    "ceng2jing1|曾经",
    "ling4wai4|另外",
    "jian3dan1|简单",
    "dao4di3|到底",
    "jue2dui4|绝对",
    "jian1chi2|坚持",
    "hao3hao3|好好",
    "ji4shu4|技术",
    "she4ji4|设计",
    "wei4lai2|未来",
    "li4yong4|利用",
    "kan4lai5|看来",
    "jian4yi4|建议",
    "yan2zhong4|严重",
    "ge4wei4|各位",
    "bao1kuo4|包括",
    "yi4yi4|意义",
    "fa3lü4|法律",
    "fu4qin1|父亲",
    "bing4qie3|并且",
    "she4hui4|社会",
    "xia4qu4|下去",
    "zheng4ming2|证明",
    "ji4zhe3|记者",
    "que4shi2|确实",
    "bu4guan3|不管",
    "fa1zhan3|发展",
    "zhi4shao3|至少",
    "jie3shi4|解释",
    "fu4ze2|负责",
    "shou3xian1|首先",
    "jiao1yi4|交易",
    "li4shi3|历史",
    "li3jie3|理解",
    "bao4dao4|报道",
    "fu4mu3|父母",
    "zhi1yi1|之一",
    "li4liang5|力量",
    "an1pai2|安排",
    "xiang4mu4|项目",
    "zao4cheng2|造成",
    "ren2sheng1|人生",
    "hui4yi4|会议",
    "xing4fu2|幸福",
    "zi4ran2|自然",
    "ze2ren4|责任",
    "shi1qu4|失去",
    "ren2min2|人民",
    "mian4dui4|面对",
    "shi4jian4|事件",
    "ya1li4|压力",
    "you2yu2|由于",
    "jie2hun1|结婚",
    "mu3qin1|母亲",
    "xun4lian4|训练",
    "tong2yi4|同意",
    "zong3tong3|总统",
    "bu4men2|部门",
    "si4hu1|似乎",
    "ji1hu1|几乎",
    "guo4cheng2|过程",
    "bao3bei4|宝贝",
    "wei4zhi5|位置",
    "fu4jin4|附近",
    "xuan3shou3|选手",
    "can1yu4|参与",
    "reng2ran2|仍然",
    "xian3shi4|显示",
    "er2shi4|而是",
    "shu3yu2|属于",
    "zhi2de5|值得",
    "ren2lei4|人类",
    "shou3shu4|手术",
    "jing1li4|经历",
    "jia1ru4|加入",
    "xiong1di4|兄弟",
    "yu4dao4|遇到",
    "di4zhi3|地址",
    "wu2lun4|无论",
    "jin3zhang1|紧张",
    "shi4shi2|事实",
    "ben3lai2|本来",
    "ji1ben3|基本",
    "zhuan1jia1|专家",
    "yi3lai2|以来",
    "fan3ying4|反应",
    "di4qu1|地区",
    "guan1zhu4|关注",
    "biao3yan3|表演",
    "jing3cha2|警察",
    "zi1liao4|资料",
    "jia4zhi2|价值",
    "xiang1dang1|相当",
    "kun4nan5|困难",
    "zhuan1ye4|专业",
    "nan2dao4|难道",
    "yu2shi4|于是",
    "gui1ding4|规定",
    "chan3sheng1|产生",
    "dui4fang1|对方",
    "zhuang4tai4|状态",
    "xin1li3|心理",
    "huan2jing4|环境",
    "jian4li4|建立",
    "ting2xia4|停下",
    "geng4jia1|更加",
    "lao3ban3|老板",
    "qi1zi3|妻子",
    "shi4chang3|市场",
    "bi4yao4|必要",
    "wei1xian3|危险",
    "qin1ai4|亲爱",
    "guan3li3|管理",
    "shi4he2|适合",
    "zheng4shi4|正式",
    "yin3qi3|引起",
];
pub const ZH_EXPERT: &[&str] = &[
    "wei2yi1|唯一",
    "ru2ci3|如此",
    "ken3ding4|肯定",
    "you3guan1|有关",
    "kong4zhi4|控制",
    "zu3zhi1|组织",
    "yong1you3|拥有",
    "zui4zhong1|最终",
    "bu4zai4|不再",
    "si3wang2|死亡",
    "zai4ci4|再次",
    "fang4qi4|放弃",
    "ji2shi3|即使",
    "jin3guan3|尽管",
    "tou2piao4|投票",
    "ke4hu4|客户",
    "ju1ran2|居然",
    "fen1xi1|分析",
    "xiang3shou4|享受",
    "fan4zui4|犯罪",
    "guan1jian4|关键",
    "guan4jun1|冠军",
    "hui1fu4|恢复",
    "tong2zhi4|同志",
    "yi4shi2|意识",
    "yi1dan4|一旦",
    "zhi2xing2|执行",
    "fen1xiang3|分享",
    "er2yi3|而已",
    "nü3xing4|女性",
    "zhi1lei4|之类",
    "tao3yan4|讨厌",
    "ren2wu4|人物",
    "ju4jue2|拒绝",
    "dui4wu3|队伍",
    "bu4zhi1|不知",
    "ying1xiong2|英雄",
    "xie2yi4|协议",
    "wei1xie2|威胁",
    "gong1ji1|攻击",
    "jing4zheng1|竞争",
    "gu1ji4|估计",
    "yi4wei4zhe5|意味着",
    "ju4le4bu4|俱乐部",
    "yun3xu3|允许",
    "cuo4guo4|错过",
    "suo3wei4|所谓",
    "an4jian4|案件",
    "zhi1zhong1|之中",
    "kong3bu4|恐怖",
    "zi4wo3|自我",
    "jian4zhu4|建筑",
    "feng1kuang2|疯狂",
    "wei3yuan2hui4|委员会",
    "you3suo3|有所",
    "yao1qing3|邀请",
    "jia1shang4|加上",
    "pai1she4|拍摄",
    "qu1yu4|区域",
    "nan2yi3|难以",
    "shuo1shi2hua4|说实话",
    "shi2shang4|时尚",
    "jia1huo5|家伙",
    "bao4zha4|爆炸",
    "zhan3shi4|展示",
    "ji1di4|基地",
    "qing2xu4|情绪",
    "zhang3wo4|掌握",
    "zui4jia1|最佳",
    "ji4yi4|记忆",
    "sheng4xia4|剩下",
    "jun1dui4|军队",
    "ji1jin1|基金",
    "she4qu1|社区",
    "shou3duan4|手段",
    "xue2hui4|学会",
    "yi2han4|遗憾",
    "bu4dui4|部队",
    "jie1chu4|接触",
    "cong1ming5|聪明",
    "pi2fu1|皮肤",
    "li4hai5|厉害",
    "zun1zhong4|尊重",
    "sun3shi1|损失",
    "ke3lian2|可怜",
    "wei4he2|为何",
    "zhong1yang1|中央",
    "xi2ji1|袭击",
    "cheng2nuo4|承诺",
    "gan3ran3|感染",
    "qi3dong4|启动",
    "nian2ling2|年龄",
    "yi1yi1|一一",
    "suan4shi4|算是",
    "ke3xi1|可惜",
    "hui2yi4|回忆",
    "hun1yin1|婚姻",
    "da3ji1|打击",
    "zhi1wai4|之外",
    "shu2xi1|熟悉",
    "shi2qi1|时期",
    "hao3yun4|好运",
    "sheng1wu4|生物",
    "ren2shi4|人士",
    "ji2tuan2|集团",
    "wei2zhi3|为止",
    "bi3ci3|彼此",
    "tui1jian4|推荐",
    "pin3pai2|品牌",
    "shi4pin2|视频",
    "zhen1xiang4|真相",
    "zan4shi2|暂时",
    "jing1xi3|惊喜",
    "you3zhe5|有着",
    "bing4du2|病毒",
    "quan2li4|权力",
    "hao2wu2|毫无",
    "chang2shi4|尝试",
    "ji2bing4|疾病",
    "zi3xi4|仔细",
    "yu2le4|娱乐",
    "ming4ling4|命令",
    "xin1shang3|欣赏",
    "zheng4ce4|政策",
    "shen2jing1|神经",
    "gao1du4|高度",
    "fa3ting2|法庭",
    "yi1bei4zi5|一辈子",
    "quan2shi4jie4|全世界",
    "lian2meng2|联盟",
    "shuo1fa3|说法",
    "ping2lun4|评论",
    "wu4zhi4|物质",
    "yi2shi4|仪式",
    "neng2fou3|能否",
    "jin4gong1|进攻",
    "zai4shuo1|再说",
    "you2qi2|尤其",
    "bing4fei1|并非",
    "fei1fa3|非法",
    "ben3shen1|本身",
    "shang4di4|上帝",
    "shi2guang1|时光",
    "bu4jian4|不见",
    "bo2shi4|博士",
    "huo4shi4|或是",
    "lang4man4|浪漫",
    "qiu2yuan2|球员",
    "dao4de2|道德",
    "bian1ji2|编辑",
    "si1ren2|私人",
    "xin1ku3|辛苦",
    "zheng4shi2|证实",
    "yi1lu4|一路",
    "yao4me5|要么",
    "ling3yu4|领域",
    "jiang1jun1|将军",
    "tou4lu4|透露",
    "bi4jing4|毕竟",
    "gong1xi3|恭喜",
    "shi1ti3|尸体",
    "lian4ai4|恋爱",
    "tuan2dui4|团队",
    "zhi3bu5guo4|只不过",
    "ge1qu3|歌曲",
    "mo2shi4|模式",
    "yi4chang2|异常",
    "dang4an4|档案",
    "xie2hui4|协会",
    "xi4bao1|细胞",
    "yi1mian4|一面",
    "zheng4zhuang4|症状",
    "shi4tu2|试图",
    "huan4zhe3|患者",
    "bo1li5|玻璃",
    "jun1shi4|军事",
    "fen3si1|粉丝",
    "zhi4yu2|至于",
    "suo3zai4|所在",
    "ling2hun2|灵魂",
    "dai4kuan3|贷款",
    "que1fa2|缺乏",
    "ling2chen2|凌晨",
    "ta1ren2|他人",
    "tao2tai4|淘汰",
    "gong1zhong4|公众",
    "shi4fang4|释放",
    "huo4sheng4|获胜",
    "da2cheng2|达成",
    "gu3li4|鼓励",
    "dan4gao1|蛋糕",
    "ben3ren2|本人",
    "xin1zang4|心脏",
    "hou4hui3|后悔",
    "dou4zheng1|斗争",
    "jia1zu2|家族",
    "mei4li4|魅力",
    "ji3yu3|给予",
    "wu3dao3|舞蹈",
    "tu1po4|突破",
];

pub fn zh_tier(tier: &str) -> &'static [&'static str] {
    match tier {
        "easy" => ZH_EASY,
        "medium" => ZH_MEDIUM,
        "hard" => ZH_HARD,
        "expert" => ZH_EXPERT,
        _ => ZH_MEDIUM,
    }
}

/// Word bank for a built-in language + tier (English by default).
pub fn tier_for(lang: &str, tier: &str) -> &'static [&'static str] {
    use crate::consts::{DE, ES, FIL, FR, JA, KO, PL, PT, TH, TR, VI, ZH};
    match lang {
        ES => es_tier(tier),
        FR => simple_tier(FR_EASY, FR_MEDIUM, FR_HARD, FR_EXPERT, tier),
        DE => simple_tier(DE_EASY, DE_MEDIUM, DE_HARD, DE_EXPERT, tier),
        PT => simple_tier(PT_EASY, PT_MEDIUM, PT_HARD, PT_EXPERT, tier),
        PL => simple_tier(PL_EASY, PL_MEDIUM, PL_HARD, PL_EXPERT, tier),
        TR => simple_tier(TR_EASY, TR_MEDIUM, TR_HARD, TR_EXPERT, tier),
        VI => simple_tier(VI_EASY, VI_MEDIUM, VI_HARD, VI_EXPERT, tier),
        KO => simple_tier(KO_EASY, KO_MEDIUM, KO_HARD, KO_EXPERT, tier),
        JA => simple_tier(JA_EASY, JA_MEDIUM, JA_HARD, JA_EXPERT, tier),
        FIL => simple_tier(FIL_EASY, FIL_MEDIUM, FIL_HARD, FIL_EXPERT, tier),
        ZH => zh_tier(tier),
        TH => simple_tier(TH_EASY, TH_MEDIUM, TH_HARD, TH_EXPERT, tier),
        _ => en_tier(tier),
    }
}

#[cfg(test)]
mod tier_dump {
    //! Read-only diagnostic support: dump exactly what `tier_for` ships, for the
    //! tier-health report. Ignored by default; run explicitly:
    //!   cargo test --lib tier_dump::dump -- --ignored --nocapture
    use crate::consts::BUILTIN_LANGS;

    #[test]
    #[ignore]
    fn dump() {
        let tiers = ["easy", "medium", "hard", "expert"];
        let mut obj = String::from("{\n");
        for (li, (lang, _, _, _)) in BUILTIN_LANGS.iter().enumerate() {
            obj.push_str(&format!("  \"{lang}\": {{\n"));
            for (ti, tier) in tiers.iter().enumerate() {
                let words = super::tier_for(lang, tier);
                let items: Vec<String> = words
                    .iter()
                    // raw UTF-8, JSON-escape only " and \ (keep CJK/Thai literal)
                    .map(|w| format!("\"{}\"", w.replace('\\', "\\\\").replace('"', "\\\"")))
                    .collect();
                let comma = if ti + 1 < tiers.len() { "," } else { "" };
                obj.push_str(&format!("    \"{tier}\": [{}]{comma}\n", items.join(", ")));
            }
            let comma = if li + 1 < BUILTIN_LANGS.len() { "," } else { "" };
            obj.push_str(&format!("  }}{comma}\n"));
        }
        obj.push_str("}\n");
        std::fs::write("tools/tierhealth/tiers_dump.json", obj).expect("write dump");
        eprintln!("wrote tools/tierhealth/tiers_dump.json");
    }
}
